projectcaluma/caluma

caluma/form/serializers.py
caluma/form/tests/test_form.py
caluma/form/tests/test_question.py

Fixes #100 
Validate input questions when reordering to be the same then on form

Validate input questions when reordering to be the same then on form

---

caluma/filters.py
caluma/form/filters.py
caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_document.py
caluma/form/tests/test_question.py
caluma/mutation.py
caluma/serializers.py
caluma/tests/fake_model.py
caluma/tests/snapshots/snap_test_schema.py
caluma/tests/test_mutation.py
caluma/types.py
caluma/workflow/schema.py

Fixes #99 
* Add specific `DjangoObjectType` implementing a default `get_queryset` and a custom `get_node`
* Add specific `DjangoFilterConnectionField` using `get_queryset` of DjangoObjectType to resolve connection
* Add `get_object` method in `SerializerMutation` based on DjangoObjectType `get_queryset`
* GlobalIDPrimaryKeyRelatedField only allows referencing objects allowed by `get_queryset` of object type
* Convert all mutations to use `SerializerMutation`

Allow overwriting of get_queryset on DjangoObjectType

---

caluma/filters.py
caluma/form/filters.py
caluma/form/tests/test_document.py
caluma/forms.py
caluma/relay.py

Fixes #109 
Current question filter expected id to be base64 encoded and ignored input when not valid. Adjusted that base64 encoded ids and plain primary keys are allowed when filtering ids or multiple choice ids.

Allow plain primary keys instead of global id when filtering

---

.flake8
caluma/collections.py
caluma/form/schema.py
caluma/mutation.py
caluma/permissions.py
caluma/settings.py
caluma/tests/test_collections.py
caluma/tests/test_mutation.py
caluma/tests/test_permissions.py
caluma/tests/test_visibility.py
caluma/types.py
caluma/user/visibilities.py
caluma/visibilities.py
caluma/workflow/schema.py

Instead of relying on naming rather use decorator with referencing import directly. This way typos can be noticed during import.

Make api of visibility and permission extensions more robust

---

requirements.txt

pip resolves idna to version 2.8 but should actually only resolve it to 2.7 as:
* cryptography requires idna >=2.1
* requests requires idna >=2.5,<2.8
Pinning works around this issue.

Pin idna to avoid dependency issue with requests

---

Dockerfile

This lead to read output in docker build which is simply confusing.

Suppress wget from writing to stderr

---

README.md
caluma/conftest.py
caluma/settings.py
caluma/user/middleware.py
caluma/user/models.py
caluma/user/tests/test_middleware.py
pytest.ini
requirements.txt

Invalid assumptions has been made that access_token is always a JWT
token. The OpenID specification doesn't require it and only a few
IAM actually implement it that way.
This change has the additional advantage that no crypthography library
is needed within Caluma context which could have vulnerabilities.

Use OpenID connect userinfo endpoint to validate bearer token

---

requirements.txt

This way someone can use default Caluma serivce with a memcache backend without having a custom `Dockerfile`.

Allow memcache to be configured as cache backend

---

README.md
caluma/settings.py
requirements.txt

Helpful when no proxy is being used which could set such.
Especially for development setup but might also be helpful
in production.

Add CORS header support

---

caluma/core/permissions.py
caluma/core/visibilities.py

For abstract classes such as `SaveDocumentAnswer` the str name is same
as base class. Hence it leads to a duplication when `Mutation` is also
overridden. It makes much more sense to check for the class name to
check for duplicates.

Avoid invalidly caused duplication errors

---

README.md
caluma/settings.py
caluma/user/middleware.py
pytest.ini

This could be a security issue if in case access token expires before
cache expires. Hence disabled by default but might still be helpful
to cache in case OpenID Connect provider is slow.

Make caching of userinfo optional

---

README.md

renovate doesn't have a badge yet

Remove obsolete pyup badge

---

.dockerignore

To avoid unnecessary docker image builds which leads to new hash
sums resp. renovate PRs.

Complete docker ignore files list

---

README.md
caluma/settings.py
pytest.ini

Fixes #201 
Per default all languages are supported and api user (e.g frontend)
decides what languages are supported.

Allow restricting of languages

---

caluma/core/filters.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/test_form.py

Default django_filter.OrderingFilter expects value to be a comma separated
which doesn't work in our case as we have actual lists from GraphQL.

Allow ordering field values to be a python list

---

caluma/form/models.py
caluma/form/serializers.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/serializers.py
caluma/workflow/tests/snapshots/snap_test_workflow.py
caluma/workflow/tests/test_workflow.py

Some cases where serializers is not used to create instance
did not properly set user and group.
However no generic solution on base model used as it would involve
thread local and only visible model classes are actually affected.

Set created by user and group on all nodes

---

caluma/user/middleware.py
caluma/user/tests/test_middleware.py

Some token especially of providers which use JWT also for access tokens
are too long for memcache key limit of 250 so the need to be hashed.

Use hashsum of token for userinfo caching

---

caluma/core/tests/test_visibility.py
caluma/core/visibilities.py

Django querysets don't support `filter` after `union`
(see https://docs.djangoproject.com/en/2.1/ref/models/querysets/#union),
which breaks simple "get by ID" queries ("get() returned more than one
Workflow -- it returned 2!").
We're fixing this by filtering our main queryset with the result of the union query.

Fix filtering on union visibility class

---

caluma/core/tests/test_visibility.py
caluma/core/visibilities.py

Before, we we're running _all_ matching visibility functions. Running
only the first (most specific) function allows overriding a generic
`Node` visibility function for specific models.
This is a backwards-incompatible change. Call your `Node`s visibility
function directly if you want to emulate previous behavior.

Visibility filters: First function "wins"

---

.travis.yml

Fixes #250
This way we also test the successful building of docker image and allows
automatic merging of docker digests with renovate.

Use docker to run tests in travis

---

caluma/core/tests/test_visibility.py
caluma/core/visibilities.py

Since empty querysets are treated as falsy the union filtering was not
applied if one class returned an empty queryset.

Fix Union visibility when queryset is empty

---

.travis.yml
README.md

There is no gain in codecov as test coverage of 100% is enforced in tests. It rather slows the CI hence removing it.

Remove codecov as testing ensures coverages

---

caluma/conftest.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_document.py
caluma/form/tests/test_form.py
caluma/form/tests/test_option.py
caluma/form/tests/test_question.py
caluma/workflow/tests/snapshots/snap_test_task.py
caluma/workflow/tests/snapshots/snap_test_workflow.py
caluma/workflow/tests/test_case.py
caluma/workflow/tests/test_task.py
caluma/workflow/tests/test_work_item.py
caluma/workflow/tests/test_workflow.py

Fixes #85 
Sometimes ordering of snapshots can be odd, hence it is difficult to rely
on snapshot to check whether a test was successful or not
it can be simply overlooked that a test actually failed even though
it should not have.

Remove snapshot tests in erroneous cases

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/serializers.py
caluma/workflow/tests/test_work_item.py

Fixes #272 
To not multiple mutations changed SetWorkItemAssigned to SaveWorkItem which additionally allows changing of meta.
With validation extension point in the future it will still be possible to differ between allowing to change meta or assigned_users.

Allow saving of meta data on work item

---

README.md
caluma/settings.py

Default Django Logging only logs info message if DEBUG is set to False.
This way we set default level to INFO in any case but user can change it with an environment variable.

Allow configuring log level

---

requirements.txt

This is possible as https://github.com/SectorLabs/django-postgres-extra/pull/73
has been merged.

Move to upstream django posgres extra version

---

caluma/workflow/serializers.py
caluma/workflow/tests/test_work_item.py

When we create a new new instance of a "multiple instance work item", we
also have to attach a new document to it (provided the work item is
linked to a form).

Create work item mutation: Create new document for work items

---

caluma/core/filters.py
caluma/form/filters.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
caluma/workflow/schema.py
caluma/workflow/tests/snapshots/snap_test_task.py
caluma/workflow/tests/snapshots/snap_test_workflow.py

This commit implements a "meta_HasKey"-filter.
For this to work, the meta-field is now a "generic.GenericScalar()".
This implementation is up for discussion and only implemented for Form.meta atm. If we decide that this is the way to go, we can implement it for the other models as well.

Implement meta-field key filtering

---

caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py

This change allows to have access to documents and even cases from
forms.
This is useful for triggering cases based on form properties (e.g.
meta).

Do not exclude documents in form schema

---

caluma/form/serializers.py

When an empty document list is passed to the validate function, a
ManyRelatedManager object was used as fallback for validation instead of the actual
documents queryset.
Fixes #313

Fix unlinking last document in table answer

---

caluma/form/serializers.py
caluma/tests/snapshots/snap_test_schema.py

The new field `is_published` on the form model is not accessible in the
CopyForm mutation. Add it to the CopyFormSerializer so it can be
set/changed with the mutation.

Add `is_published` to the CopyFormSerializer

---

caluma/workflow/serializers.py
caluma/workflow/tests/snapshots/snap_test_work_item.py
caluma/workflow/tests/test_work_item.py

With multiple instance tasks, comparing the amount of tasks referenced
by a flow to the amount of finished related work items doesn't work
anymore. This makes sure that each task is checked for completion
individually.

Fix: Continue workflow after completing multiple instance task

---

caluma/form/serializers.py

I missed this in the tests because both values are filled with the same
test data.

Fix reference in form answer validation

---

caluma/form/serializers.py

The actual required check comes later in the validator.

String Answer: Allow blank values on serializer

---

caluma/form/models.py
caluma/form/tests/test_document.py

The family field represents the identifier of the topmost document of
the structure. When recursively creating a document structure, we need
to pass down the family, otherwise it will be set anew for each sub
document, defeating the purpose.

Bugfix: When creating a document tree, set the family

---

caluma/user/middleware.py

* Authorization header had a colon after the name
* Use introspect-endpoint if 401 or 403

[FIX] typo and status_code

---

caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/test_document.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/serializers.py
caluma/workflow/tests/snapshots/snap_test_case.py
caluma/workflow/tests/test_case.py
requirements.txt

We need to be able to update the `meta` field of cases and documents.
The current implementations only allowed creation.
While we're at it, rename the `startCase` mutation to `saveCase` via
proper deprecation (yay GraphQL!).
The `startCase` mutation is not modified in any way, but the `saveCase` has an optional ID parameter to allow updating cases.

Feature: Allow updating documents and cases

---

caluma/form/models.py

This commit removes the slugification of object names for file in minIO.
Caluma and minIO can handle special characters, so there is no need for
this.
closes #387

Do not slugify the object name of files

---

.gitignore
caluma/core/filters.py
caluma/core/tests/test_meta_filters.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/tests/snapshots/snap_test_schema.py

This new filter is able to filter any node that has a meta field by the
meta field's value, as follows:
query foo {
allDocuments (metaValue: {key: "foo", value: "hello world"}) {
...
}
}
This will return all documents whose meta field has a key named "foo"
with the value "hello world".
An optional parameter can be given to the filter to configure the lookup
type:
metaValue: {key: "foo", value: "hello", lookup:STARTSWITH}
This would change the filter to startswith (prefix search). Also
available lookup methods are EXACT (default if parameter is left out,
and CONTAINS (which does a case-insensitive lookup)).

New filter on MetaFilterSet: metaValue

---

caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py

BREAKING CHANGE: If you've been manually parsing the JSONString of a
meta field, you can remove that code - meta is automatically expanded now.

fix(API): use GenericScalar for meta fields

---

caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_answer.py
caluma/form/tests/test_answer.py
caluma/tests/snapshots/snap_test_schema.py

This commit adds a removeAnswer mutation.
So if a user answered an optional question, there is now a way to completely
remove it's answer.
Closes #392

Add removeAnswer mutation

---

caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_answer.py
caluma/form/tests/test_answer.py
caluma/tests/snapshots/snap_test_schema.py

The removeAnswer mutation always returned `FileAnswer` as __typename.
This commit fixes that, so that the returned `__typename` always matches
the answer that was removed.

Fix returning __typename for removeAnswer mutation

---

caluma/form/serializers.py
caluma/tests/snapshots/snap_test_schema.py

This was set to `__all__` which is obviously too much.
This commit adds the right fields.
Closes #411

Fix SaveDocumentFileAnswerSerializer fields

---

README.md
caluma/data_source/data_sources.py
caluma/data_source/tests/data_sources.py
caluma/form/factories.py
caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/test_document.py
caluma/form/tests/test_validators.py
caluma/form/validators.py
caluma/workflow/serializers.py
caluma/workflow/validators.py

This PR adds validators for answers to DynamicChoiceQuestion and
DynamicMultipleChoiceQuestion.
For this to work, all validators need access to the `info`-object.
Closes #412

Add validators for dynamic choice options questions

---

caluma/user/middleware.py
caluma/user/tests/test_middleware.py

This commit fixes the error handling of `user.middleware`.
Before, if the unserinfo endpoint returned 401 or 403 and NO
introspection endpoint was configured, the user was left unset.
Now we raise the proper exception.
Closes #422

Fix OIDC-middleware error handling

---

caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py

The type of `parentAnswers` on `Document` and `answer` on `File`
was not explicitly set.
This commit sets the type for them.
Closes #382

Fix type of Document.parentAnswers

---

caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py

This fix caused issues in "getFileAnswerInfo": "FormAnswer" is returned.
This reverts commit 7920a276a74d5f7e5beb0b92e845640d4850fcfb.

Revert "Fix type of Document.parentAnswers"

---

caluma/form/serializers.py
caluma/tests/snapshots/snap_test_schema.py

Static content is also supposed to be the primary field type for custom
field overrides. For those overrides, no actual static content is
required.

feat(static): make static question content optional

---

caluma/form/factories.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/test_document.py
caluma/form/tests/test_type.py
caluma/tests/snapshots/snap_test_schema.py

Graphenes auto type detection doesn't work reliably with our different
Question and Answer types.
This commit adds a subclass of our subclass of DjangoObjectType with
support for resolving Question and Answer types.
Additionally the type is explicitly set for `parent_answers` of `Document`
and `answer` on `File`.
Also updated the `AnswerFactory` to correctly set float and int values for
their respective Answers.
Closes #432

Fix returned types

---

caluma/form/tests/test_validators.py
caluma/form/validators.py

`validate_required()` on `DocumentValidator` used a "if not" condition.
With this commit, it checks explicitly for `None` and `""`.
Closes #435

Fix saving table answers with value 0

---

caluma/form/tests/test_validators.py
caluma/form/validators.py

This commit adds a validator to check if the supplied `dataSource`
exists.
Closes #427

Add validation for data_source on Question

---

caluma/core/types.py
caluma/data_source/schema.py
caluma/data_source/tests/snapshots/snap_test_data_source.py
caluma/data_source/tests/test_data_source.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/snapshots/snap_test_format_validators.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_document.py
caluma/form/tests/test_format_validators.py
caluma/form/tests/test_question.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/tests/snapshots/snap_test_case.py
caluma/workflow/tests/snapshots/snap_test_task.py
caluma/workflow/tests/snapshots/snap_test_work_item.py
caluma/workflow/tests/snapshots/snap_test_workflow.py
caluma/workflow/tests/test_case.py
caluma/workflow/tests/test_task.py
caluma/workflow/tests/test_work_item.py
caluma/workflow/tests/test_workflow.py

This commit implements `totalCount` for connections as per graphQL spec.
Closes #404

Implement totalCount for connections

---

renovate.json
requirements-dev.txt

This commit enables auto-merge for Docker digests and dev dependencies.
Unfortunately renovate does not support `devDependencies` for pip, so
all those have to be explicitly listed in the renovate config.
Closes #442

Enable auto-merge for renovate for certain dependencies

---

README.md

`CORS_ORIGIN_WHITELIST` now must contain the scheme.

Updated README in regard to django-cors-headers 3.0.0

---

caluma/core/filters.py
caluma/tests/snapshots/snap_test_schema.py

This is required if we want to filter by e.g. numbers instead of
strings.

fix(meta filter): use GenericScalar for meta filter value

---

caluma/core/filters.py
caluma/form/tests/test_filter_by_answer.py

Date answers use a dedicated field, so we should use it instead of
`value` when searching

Fix HasAnswerFilter: correct field for date types

---

caluma/core/filters.py
caluma/core/tests/test_pagination.py
caluma/tests/snapshots/snap_test_schema.py

This commit adds offset pagination with `limit` and `offset` filters.
This can alternatively be used instead of the already implemented cursor based
pagination.
Closes #459

feat(pagination): implement offset pagination

---

caluma/core/filters.py
caluma/core/pagination.py
caluma/core/tests/test_pagination.py
caluma/core/types.py
caluma/form/schema.py

This commit implements a fix for
https://github.com/graphql-python/graphql-relay-py/issues/12
The project `graphql-relay-py` seems unmaintained, so there is
little hope that
[this PR](https://github.com/graphql-python/graphql-relay-py/pull/14)
gets merged any time soon.
Closes #469

Fix hasPreviousPage

---

caluma/core/filters.py
caluma/core/forms.py
caluma/form/filters.py
caluma/form/tests/test_root_document_filter.py
caluma/tests/snapshots/snap_test_schema.py

This is intended to improve loading speed so you don't need to build a
large nested query anymore, which should speed up data retreival:
```graphql
query foo ($root: ID!) {
allDocuments(rootDocument: $root) {
edges {
node {
id
}
}
}
}
```
This should get you all documents regardless of nesting level. Fetching the corresponding answers for them should then allow you to get the whole structure in a flat result

Introduce family filter for documents

---

caluma/form/jexl.py
caluma/form/models.py
caluma/form/tests/test_jexl.py
caluma/form/validators.py

This commit makes `form` and `rootForm` accessible
in JEXL expressions.
Closes #503

Make form accessible in JEXL

---

caluma/core/jexl.py
caluma/core/tests/test_jexl.py

Profiling the validation process showed that a lot of time is spent in
parsing (not even executing!) the JEXL expressions.
Caching the parsed expressions (and shortcutting simple "true" / "false"
expressions) improved the validation time for a large-ish document
structure from roughly 46s on my machine down to 23s.
Of the remaining 23s, 17s are spent fetching data from the DB, which
will be sped up when the "flattening" of the document structure is
merged

Performance improvements

---

caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/snapshots/snap_test_filter_by_answer.py
caluma/form/tests/test_document.py
caluma/form/validators.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/tests/snapshots/snap_test_workflow.py

This allows validating documents without trying to complete a work item.
The query will return a list of errors from the validator (as far as
possible, as it currently works with exceptions when something happens)
Implements #509 via this query:
```graphql
query ValidateFoo {
documentValidity(
id: "RG9jdW1lbnQ6MDFjNTgwYmItZmU1Zi00ZmY2LTlmMDctMWVlNDJlNjVhNmNl"
) {
edges {
node {
id
isValid
errors {
slug
errorMsg
}
}
}
}
}
```
resultin in a response like this
```json
{
"data": {
"documentValidity": {
"edges": [
{
"node": {
"id": "01c580bb-fe5f-4ff6-9f07-1ee42e65a6ce",
"isValid": true,
"errors": []
}
}
]
}
}
}
```

New: query for validating documents

---

caluma/core/filters.py
caluma/core/tests/test_meta_filters.py
caluma/tests/snapshots/snap_test_schema.py

BREAKING CHANGE: check used metaValue and change them from single value to list.
In some projects, we need to filter by multiple meta values. This change
allows passing a list of meta filters instead
Obsoletes #543

feat(filters)!: metaValue filter now takes a list

---

requirements.txt

Renovate long ago updated the dependency to the newest already where
this is comment got fixed.

Remove obsolete comment of urllib3 deps

---

caluma/core/types.py
caluma/form/tests/test_document.py

* if totalCount is requested only run count query once
* avoid count query when no pagination arguments are set
For large forms this is a approximate improvement of 15%

Avoid count queries when possible

---

caluma/core/filters.py
caluma/core/types.py

Those comments got actually resolved with graphene-django 2.3.2 see #493

Adjust obsolete type comments

---

caluma/settings.py

Those files are not exposed in uwsgi.ini so there are no security implications.

Expose static files to make GraphiQL load again

---

caluma/user/middleware.py

Once a user is set on request authentication is already passed and we can exit.

Check authentication only once

---

caluma/settings.py

We don't use promises so this is a performance gain of 10% in large calls.
This also means though that data loaders won't work which we currently do
not use.

Disable async trampoline

---

caluma/core/filters.py

Constructing a django filter form is a performance hit and should only be done when there are actual filters.

Avoid calling of filterset class when there are not filtering args

---

docker-compose.override.yml

If the user already downloaded the release image and then decides to start
development, docker will use the already cached image, no rebuild is triggered.
By using the tag latest-dev instead of latest, docker can't use the cached
image.
**Update**: Changing Title and Description because the root-cause is different, the old Issue was:
Title: Add a way to install dev_requirements to testing-how-to
Maybe I missed something, but I had to do this to run the testing-commands.

Use different tag for caluma development

---

.flake8

This is the cannonical way to deal with black.

Set max-line-length = 88 instead of ignore E266

---

caluma/core/filters.py
caluma/form/tests/test_order_by_meta.py

Additionally this avoids annotate which would be added even though ordering
by meta field is not really used.
Fixes #608

Keep json field value type when ordering

---

README.md

This is not the way we want to implement ordering of meta fields see
#616 for different suggestion.
For now we remove it from the documentation not to promote it to users
so this feature can easily be removed later on.

Remove `META_FIELDS` from documentation

---

caluma/form/schema.py

This makes sure that it is understood when isRequired is actually evaluated.

Clarify isRequired expression on question

---

caluma/core/filters.py
caluma/core/tests/test_meta_filters.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
caluma/workflow/tests/test_work_item.py

This commit transforms the `MetaValueFilter` into a more generic
`JSONValueFilter`.
This filter is then used for a `caseMetaValue` filter to the workitems. This
allows for filtering WorkItems based on meta field values.
Closes #610
BREAKING CHANGE: `MetaValueFilterType` has been renamed to
`JSONValueFilterType` and `MetaLookupMode` to `JSONLookupMode`.

feat(WorkItems): add caseMetaValue filter

---

caluma/form/jexl.py
caluma/form/tests/test_validators.py
caluma/form/validators.py

* There is no need for answer_tree anymore as of #505
* parent doesn't exist and can be removed
* requiredness does not to be inherited as a form question does actually
have answers.

Remove left overs of validation answer tree

---

caluma/core/filters.py
caluma/core/tests/test_meta_filters.py

This fixes a regression introduced in #631: `KeyTextTransform` casts the Boolean `True` to the String `"true"`, which is not what we want when we're filtering for boolean values.

fix(filters): Fix meta filtering with boolean values

---

caluma/form/filters.py
caluma/form/tests/test_search_answers.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
requirements-dev.txt

This introduces a filter named `searchAnswers` that allows you to search
text within documents/cases across multiple answers.
The way it works is you pass a list of questions to search, and a search
string. The search string is split by words. Each word must then be
found in at least one answer for a document/case to show up.
You may optionally provide a lookup type: `STARTSWITH`, `TEXT`,
`CONTAINS`.
Note that depending on the database, those may or may not perform well,
as we do not at this point in time preemptively optimize by creating
indexes etc.
/cc @fkm

feat(filters): Text search across multiple answers

---

.gitignore
.travis.yml
CONTRIBUTING.md
commit-msg
commitlint.config.js

This commit adds enforcement of [conventional
commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) to the
pipeline.
Additionally it adds a `commit-msg` hook for git.
Closes #532

feat: enforce conventional commits

---

README.md
uwsgi.ini

The defaults of uWSGI are not good. These are the settings researched by
Peter Sperl at [bloomberg](https://www.techatbloomberg.com/blog/configuring-uwsgi-production-deployment/?sf104898833=1) and @winpat.
I checked that uWSGI accepts overriding these settings by
environment-variables and composed gist for the admins wanting to change
our defaults. https://git.io/JemA2
It is gist because it is interesting for other projects and caluma doesn't
have a place for this kind of documentation, yet. It would have been out of
place in the README which is about caluma not uWSGI.

chore(uwsgi): Sane defaults for uWSGI

---

caluma/form/historical_schema.py
caluma/form/tests/snapshots/snap_test_history.py
caluma/form/tests/test_history.py
caluma/tests/snapshots/snap_test_schema.py

This commit implements the argument `asOf` for all related types in the
historical schema.
This removes the need for accessing variables from other types (i.e. the
top level `documentAsOf`). But also it gives us much more flexibilty
when constructing queries.
Closes #683

feat(history): support asOf per type

---

caluma/core/management/commands/cleanup_history.py
caluma/form/tests/test_command.py
requirements.txt
setup.cfg

This commit adds a cleanup command for historical records:
```
usage: manage.py cleanup_history [-h] [--no-clean-dups] [--dry] [-k KEEP]
[--version] [-v {0,1,2,3}]
[--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback]
[--no-color] [--force-color]
Cleanup historical records.
optional arguments:
-h, --help            show this help message and exit
--no-clean-dups
--dry
-k KEEP, --keep KEEP  Duration we want to keep the records. E.g. '6 months',
'1 year'. Uses dateparser.
```

feat(history): add cleanup command

---

caluma/form/historical_schema.py
caluma/form/tests/snapshots/snap_test_history.py
caluma/form/tests/test_history.py
caluma/tests/snapshots/snap_test_schema.py

This commit exposes the original document id as `documentId` on a
`HistoricalDocument`.

feat(history): expose original document id

---

README.md
caluma/form/tests/test_command.py

This commit adds a section about cleanup commands for historical records
to the README.md.
Drive-by typo fix in command test.

docs(history): document cleanup commands in README

---

docs/exam-design.svg
docs/exam-execution-1.svg
docs/exam-execution-2.svg
docs/exam-execution-3.svg
docs/exam-execution-4.svg
docs/workflow-entities.svg

Since I still had rendering issues with the current SVGs, I replaced the fonts by web-safe fonts.

chore(docs): use websave fonts for svgs

---

caluma/core/filters.py
caluma/core/ordering.py
caluma/core/tests/test_ordersets.py
caluma/form/filters.py
caluma/form/ordering.py
caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
caluma/workflow/schema.py
docs/graphql.md

We want to separate filtering and ordering syntactically, so it doesn't
make sense to allow filtering in the filter[] list in the first place.

Filters: Syntactic separation of ordering and filtering

---

.pre-commit-config.yaml
.reuse/dep5
.travis.yml
LICENSE
LICENSES/AGPL-3.0-or-later.txt
LICENSES/CC0-1.0.txt
README.md
requirements-dev.txt
setup.py

BREAKING CHANGE: switch to AGPL-3.0-or-later
* Initialize reuse-tool
* Add AGPL-3.0-or-later via dep5 for caluma/*.py
* Add CC0-1.0 via dep5 for metadata/config/info files
- Files that are below the threshold of originality
* Add reuse lint to travis and pre-commit
(Followup from @ganwell's fork as he's on vacation)

chore(reuse): switch to AGPL-3.0-or-later, add reuse-tool

---

caluma/core/tests/test_ordersets.py
caluma/form/ordering.py

Ordering by answer value only worked directly on documents,
as the order-by value was joined naively to the outer "pk"
instead of the pk of the document table.
This fixes the problem so that everything that's ordered
by an answer value is now working correctly

fix(ordering): fix ordering by question value

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py

Fixes #753 by allowing work items to be ordered by deadline again

fix(ordering): reintroduce ordering by deadline on work items

---

caluma/form/schema.py
caluma/form/tests/test_question.py

In the allQuestions query, do not return the same question multiple
times if it is used in more than one form.
This evaded noticing until now because we usually use the `slugs=[]..`
filter, which does the `distinct()` call for us.

fix(questions): do not return questions multiple times

---

.reuse/dep5
LICENSE
LICENSES/GPL-3.0-or-later.txt
README.md
setup.py

Based on the discussion in issue #751, we reevaluated our goals. We want
-  diverse uses and integration of Caluma
-  Caluma to remain public as Free Software
-  an active community
-  to guarantee mutual benefit to our contributors
We found that the definitions in AGPL aren't as clearcut as we wished; therefore, we want to switch to GPL-3.0-or-later. GPL will support all of our goals, with a minor draw-back: Not every last modification is guaranteed to end up in public. Which isn't that bad and it resolves all discussion about configuration.

chore(license): switch main license to GPL-3.0-or-later

---

caluma/form/filters.py
caluma/tests/snapshots/snap_test_schema.py

Question slugs are strings, but should be presented as IDs,
as they are when used in mutations. This leads to duplicate
code in the clients when needing to pass the quesiton ID once
as string and once as ID.

fix(filters): question id/slug should be of type id

---

caluma/core/jexl.py

This method used to contain some shortcut logic, but now it
just passes the call to super(), which we can just as well leave out

refactor: remove method that's not used anymore

---

caluma/form/filters.py
caluma/form/historical_schema.py
caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/snapshots/snap_test_filter_by_answer.py
caluma/form/tests/test_document.py
caluma/form/tests/test_validators.py
caluma/form/validators.py
caluma/tests/snapshots/snap_test_schema.py

This commit adds the possibility to save/query Answers with `null`
values.
It also adds a new lookup mode `ISNULL` to the `HasAnswerFilter`. If
this lookup mode is used, the provided `value` (if any) is ignored.
Since graphql-core doesn't support `null` literals yet, the way for setting
the value of an Answer to `None` is to omit the `value` field
altogether.
Closes #790 and #800 
BREAKING CHANGE: `Answers` are now allowed to have `null` values.

feat(form): allow Answers with empty value

---

.gitignore
CONTRIBUTING.md

I first thought it makes no sense because we use docker, but I needed to install the packages for my editor. So its nice to have the commands in the documentation.

docs: explain how to use pipenv

---

caluma/form/historical_schema.py

This commit optimizes `historical_qs_as_of()` so that the amount of
queries is significatly reduced and it returns a `Queryset()` instead of a
list.

fix(history): optimize `historical_qs_as_of`

---

caluma/core/permissions.py
caluma/core/tests/test_permissions.py

Before, the `has_permission` and `has_object_permission` decorators
would need a separate function for each Mutation.
Now, the same function can be decorated for multiple mutations, reducing
the amount of code if some mutations share the same permission logic.
Example:
```python
class CustomPermission(BasePermission):
@has_permission(FirstMutation)
@has_permission(SecondMutation)
def has_permission_for_both(self, mutation, info):
return False
```

feat(permissions): make permission decorators chainable

---

caluma/form/tests/test_validators.py
caluma/form/validators.py

When validating, we must only consider questions directly within a given
form, not all below.  This caused answers to be validated that should
not have been.

fix(validation): Validate dependencies correctly

---

.travis.yml
CONTRIBUTING.md
setup.py

This kind of just happend:
1. I needed a way to install the environment for my editor, so that completion works, pipenv was very easy to use
2. Then managing the dependencies and running multiple databases for #814 was a pain, so I started to use pipenv for development
3. Then @sbor23 asked how to do local development and I defined a proper workflow
4. Then I realized that there are certain common mistakes, so I coded the setup of pipenv in setup.py
5. And after all this, it made sense to also test in the pipenv, so there are no surprises for developers deciding do local development

add pipenv workflow for local development

---

caluma/core/filters.py
caluma/core/types.py
requirements.txt

* Remove insignificant performance hack. Performance profiling is known to have a variance of 20% - 40%, only improvements of %50+ should be considered, especially when hacking the internals
of another library.
* Update to graphene v2.0.1 since graphene-django v2.7.1 depends on that version.
* Adapt to refactoring of DjangoConnectionField. We inject our version of
connection_from_list, connection_from_list_slice.
Replaces #837

chore(deps): update to graphene-django v2.7.1

---

setup.py

Some situations require running Caluma inside an existing Django
project, instead of a standalone service. This aims to provide
this ability.
WIP, I'm not entirely sure what's needed to get this to work just yet. Experimenting around...

feat: make caluma installable as django app

---

.reuse/dep5
caluma/form/fixtures/form-fixture.json

The form fixture represents a minimal form as it's used by the
ember-caluma addon. It includes all question types apart from dynamic
questions.
This is intended to be development aid, reducing the burden to have setup some test data.
It can be loaded into the local project by running `python manage.py
loaddata caluma/fixtures/form-fixture.json`.

chore: include minimal form fixture

---

caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

Questions can not only be hidden by evaluating their is_hidden expression
but also when they're part of a subform, where the containing form question
is hidden. We need to check for that case as well, which didn't happen till now.

fix(validation): correctly handle indirectly hidden questions

---

.travis.yml
setup.cfg

We had too much trouble with automatic releases not detecting breaking
changes. That's why we decided to go back to manual releasing and using
`python-semantic-release` just as support tool for writing release
notes.

chore(release): remove semantic-release from pipeline

---

caluma/caluma_form/tests/test_validators.py

Test more distinct cases for table answers.
Previously it was not clear whether some tests should throw a ValidationError
because the jexl couldn't be evaluated or because the requiredness was
not met. So we add separate test cases for each.
Resolves https://github.com/projectcaluma/caluma/issues/870

chore: clarify validate_table tests

---

CHANGELOG.md
caluma/caluma_metadata.py

Note the features / fixes were marked as refactor/chore in git and
thus semantic-release didn't really want to create a new version.

chore: version bump to 5.1

---

caluma/caluma_data_source/data_source_handlers.py
caluma/caluma_data_source/data_sources.py
caluma/caluma_data_source/tests/data_sources.py
caluma/caluma_data_source/tests/test_data_source.py
caluma/utils.py

The documentation states, not only lists are allowed inside `get_data()`
results, but also other iterables. This was not true.
This commit makes sure, that also tuples and other iterables are
correctly handled.

fix(data_sources): fix validation of dynamic answers

---

caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_validators.py

To get the "value" of a file answre, we need to return the `file` attribute.
This didn't happen, causing requiredness checks for file answers to fail
despite the answer actually having a file

fix(validation): file answers need special treatment

---

caluma/caluma_form/historical_schema.py
caluma/caluma_form/schema.py
caluma/caluma_workflow/schema.py
caluma/tests/snapshots/snap_test_schema.py

This commit removes obsolete `exclude` entries for some types.
Additionally it adds some info about the `is_required` field on
`StaticQuestion`.

chore(schema): remove obsolete excludes

---

docs/maintainers.md

This commit adds some info to `maintainers.md`about the handling of
deprecations in caluma.

chore(docs): add info about `Deprecations` issue

---

caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

When a form question is not required, it should not swallow up any
requiredness errors from missing answers below it.
Also, a non-required table question should not lament missing rows
if it is not required itself.

fix(validation): handle is_required correctly in nested questions

---

caluma/caluma_form/management/commands/create_bucket.py
caluma/settings/__init__.py
caluma/settings/caluma.py
caluma/settings/django.py

This commit splits the settings file. `main.py` contains settings for
the django project used by caluma service. `module.py` contains the
caluma specific settings and gets imported by `main.py`. This allows
third party projects that integrate Caluma to just import the settings
in `module.py`.
Documentation for using Caluma as modules is in the works. PR will follow.

feat(pypi): split settings file

---

README.md
docs/django-apps.md
docs/interfaces.md

This commit adds some documentation about
* using the caluma django apps inside an existing django project
* supported interfaces.
Related to #940
Closes #941

docs(interface): add docs about usage of django apps and interfaces

---

docs/django-apps.md

This commit removes some information from `django_apps.md` that was deemed
unnecessary and potentially confusing for new users.

chore(docs): simplify apps docs

---

Dockerfile
caluma/settings/__init__.py
caluma/wsgi.py
manage.py
setup.cfg

Because of the * import in `settings.__init__`, it's was not possible to
just load the caluma specific settings, without implicitly also loading
the django project settings.
This commit fixes that. The downside of this fix is, that the settings
module is not called `caluma.settings` anymore, but
`caluma.settings.django`.

fix(pypi): fix loading of caluma settings

---

caluma/caluma_core/urls.py
caluma/caluma_user/views.py
caluma/urls.py
docs/django-apps.md
docs/interfaces.md

This commit moves the graphql view to the core app and renames it to
`CalumaGraphQLView`. Additionally it adds a `caluma_core.urls` that gets
included in the main `urls.py`.
This means third-party projects can include the caluma urls like this:
```python
from django.conf.urls import include, url
urlpatterns = [
url(r"", include("caluma.caluma_core.urls")),
]
```

chore(urls): move view and add urls.py to core

---

caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

When evaluating JEXL expressions, you can use the word `form` to get
the name of the top form. This wasn't the case ror row forms until now
(but only in is_hidden evaluation).  Now, `form` always points to the
root form of the document.

fix(validation): the word "form" should always be the root form

---

caluma/caluma_form/jexl.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_jexl.py
caluma/conftest.py
docs/validation.md

Extend and cleanup JEXL evaluation, so more information can be accessed.
This is considered a proposal. Implementation details, especially regarding the "new" JEXL syntax now introduced, are open for discussion.
New with this PR, you'll have access to an `info` object in question JEXL expressions that provides some useful information:
- `info.root.form` - Same as `form`, gives the root form's slug
- `info.form` - The direct form where the question resides. Could be a row
form if the question is within a table, or a FormQuestion's form, etc.
- `info.parent.form` - The form above the current form. May be useful in
deeply nested structures.
While we're at it, I've also started documenting the other things we have, such as the `form` variable and our custom transforms and operators. The idea …

feat: Extend JEXL

---

caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py

When a question is hidden, it's answer transform should not return a value,
even if an answer exists.

fix(jexl): answer transform shouldn't return value for hidden questions

---

caluma/caluma_workflow/migrations/0022_workitem_name_description.py
caluma/caluma_workflow/tests/test_migrations.py

This commit fixes the migrations that adds `name` and `description` to
the `WorkItem` model. Historical lookups of `id` must always use
`filter`.

fix: fix WorkItem migration

---

caluma/caluma_data_source/tests/test_data_source.py

#814 creates a lot of chicken and egg problems. I want to at least push simple fixes to caluma.
The graph*-3.0 projects try to validate all inputs and prevent all implicit conversion.

fix(graph*-3.0): only accepts integer or string as id

---

caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py

This commit fixes the form validation.
Given a structure like this:
```
f:topform
q:formquestionbranch - hidden=false
f:subformbranch
q:depquestion2 - required = 'subquestion2'|answer=='bluh'
q:formquestion - hidden=variable
f:subform
q:subquestion1 - hidden=false
q:subquestion2 - hidden=false
q:depquestion1 - required = 'subquestion1'|answer=='blah'
d:topdoc f=topform
a:subanswer1 q=subquestion1, value='blah'
a:subanswer2 q=subquestion2, value='bluh'
```
The requiredness of `depquestion2` was wrongly evaluated to `True`,
because it couldn't reach `formquestion` and everything below.
This commit fixes the validation, so it can reach all forms in the
document.

fix(validation): fix evaluating requiredness from branch forms

---

caluma/caluma_core/tests/test_validations.py
caluma/caluma_core/validations.py
caluma/caluma_user/models.py
docs/extending.md

This commit simplifies manual setting of the `created_by_group` field
from within validations.
Before, in order to override the chosen group, one had to prepend it to
the list `OIDCUser.groups`. Now, one can just set the property:
`user.group = "foo"`.
Closes #614

feat: make created_by_group settable

---

caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py

When evaluating a JEXL expression (is_required / is_hidden in questions),
we need to make sure that the context is set to the correct form /
field set.  Otherwise, we may end up with cross talk between table rows,
for example, as the answer transform would just fetch the first answer,
which may be from another row than what we're currently looking at.
While we're at it, also fix the caching behaviour during evaluation: The
cache key used must be local to the document of the answer, as otherwise
the value might be wrong for table answers (assume row 1 evaluated to
another result than row 2 would, then we wouldn't notice)

Fix answer transform in table rows

---

caluma/caluma_form/jexl.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/validators.py

When validating row documents, a question may be "visible" in another
row and hidden in the current one. However the `visible_questions` list
is global and is used mainly to speed up database access.
When evaluating requiredness, we also need to check if the question is
visible *locally*.
Follow-Up to #1036

fix(validation): the requiredness check needs local context

---

caluma/caluma_core/filters.py
caluma/caluma_workflow/tests/test_date_filters.py
caluma/tests/snapshots/snap_test_schema.py

Introduce filters `createdBefore` and `createdAfter`. Those can be used to limit
results to objects created within a given time range when used in combination.
Note that The "After" filter is inclusive, while the "Before" filter is exclusive.
This is done so that clients don't need to fiddle with filter values when they
want to filter for one specific day, for example.
/cc @fkm

feat(filters): add filters for object creation dates

---

README.md
caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_case.py
caluma/caluma_workflow/utils.py
docs/interfaces.md

When caluma is used as a django app, it is often desireable to trigger
specific mutations by calling python APIs directly (instead of the
GraphQL API). This shows how we could go about offering a Python API for
starting cases that mirrors what the GraphQL API offers via saveCase: We
extract the business logic out of the serializer into a domain logic
class which is then used in a public method exposed in an api module.
Closes #1046

feat(architecture): expose start case logic in public python api module

---

CONTRIBUTING.md
setup.py

'id --user' is not POSIX and missing on some systems

docs(pipenv): switch to 'id -u' when creating a pipenv

---

caluma/caluma_workflow/filters.py
caluma/tests/snapshots/snap_test_schema.py

Since a workflow can have multiple allowed forms it makes sense to allow
filtering for a set of document forms.

feat(allCases): add documentForms filter for allCases graph

---

caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_workflow.py

Remove only flows of the same workflow when creating WorkflowFlows.
Previously, all flows connecting from the same task were deleted upon
using the AddWorkflowFlow migration. Now we filter using the given
workflow instance, allowing reuse of the same task in multiple worklows.
Fixes #1065

fix(workflow): make tasks reusable in workflow flows

---

caluma/caluma_core/tests/test_inversible_filters.py
caluma/caluma_core/tests/test_meta_filters.py
caluma/caluma_core/tests/test_mutation_params.py
caluma/caluma_core/tests/test_ordersets.py
caluma/caluma_core/tests/test_pagination.py
caluma/caluma_data_source/tests/test_data_source.py
caluma/caluma_form/tests/test_answer.py
caluma/caluma_form/tests/test_document.py
caluma/caluma_form/tests/test_filter_by_answer.py
caluma/caluma_form/tests/test_form.py
caluma/caluma_form/tests/test_format_validators.py
caluma/caluma_form/tests/test_history.py
caluma/caluma_form/tests/test_option.py
caluma/caluma_form/tests/test_question.py
caluma/caluma_form/tests/test_root_document_filter.py
caluma/caluma_form/tests/test_search_answers.py
caluma/caluma_form/tests/test_type.py
caluma/caluma_workflow/tests/test_base_filters.py
caluma/caluma_workflow/tests/test_case.py
caluma/caluma_workflow/tests/test_date_filters.py
caluma/caluma_workflow/tests/test_events.py
caluma/caluma_workflow/tests/test_task.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/caluma_workflow/tests/test_workflow.py
caluma/conftest.py
caluma/tests/test_schema.py
requirements.txt

graphene-django does a good job pinning the version for graphql-core,
graphene and graphql-relay.
So we remove them from our requirements and let graphene-django handle
these.

chore: remove version pinning for subdependencies

---

caluma/utils.py

The log message didn't get rendered properly due to missing fstring markup.

fix(log): use fstring to log fstring message

---

caluma/caluma_core/management/commands/cleanup_history.py
caluma/caluma_core/tests/test_commands.py
caluma/caluma_form/tests/test_command.py
docs/historical-records.md

Add option -d, --dangling, cleaning up instances with missing relation.
For example, if a question was deleted, the historical answers
referencing this question might have a broken reference.
Passing -d will include theses instances for deletion.
We drop --keep, this functionality is now provided by upstream simple_history's `clean_old_history`

feat: add --dangling option for cleanup_history command, drop --keep option

---

caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/serializers.py
caluma/tests/__snapshots__/test_schema.ambr

Skipping a work item causes the same side effects for the workflow as
completing it. Therefore it also needs the new context to function
properly.

fix(workflow): enable context for skipping work items

---

caluma/caluma_core/events.py
caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/events.py
caluma/caluma_workflow/serializers.py
caluma/tests/__snapshots__/test_schema.ambr
docs/events.md

This commit adds the `context` property for all workitem and case
mutations. It also passes that context to all events emitted in those
mutations (and API functions) since the context is very helpful
sometimes in event handlers.

feat(workflow): add context for all case and workitem mutations

---

caluma/caluma_workflow/api.py

The useless refetching of the models before updating them caused a
difference between the value in the DB and the return value since the
return value was not altered or refreshed from the DB.

fix(api): fix the return object of api methods

---

caluma/caluma_workflow/factories.py

For some reason this was never a problem, but now that we import the module in downstream project it's unable to import `DjangoModelFactory`.
I have several questions...

fix(test): import DjangoModelFactory from actual module path

---

requirements-dev.txt
requirements.txt

This fixes #1055, #1102, #1120, #1122, #1136, and #1144

chore: bump versions of several dependencies

---

caluma/caluma_workflow/domain_logic.py
docs/events.md

This event should always be sent when a work item has been completed,
even if the workflow doesn't continue (e.g. for multiple instance tasks
that remain open).

fix: always send post_complete_work_item event

---

caluma/caluma_workflow/migrations/0020_case_families.py

When a case's parent work item points to itself, the migration will
loop forever. Catch this situation and abort in that case.

fix(migrations): do not hang in migrations on broken data

---

caluma/caluma_core/models.py
caluma/caluma_form/api.py
caluma/caluma_form/domain_logic.py
caluma/caluma_form/models.py
caluma/caluma_form/serializers.py
caluma/caluma_form/tests/__snapshots__/test_document.ambr
caluma/caluma_form/tests/test_document.py
caluma/caluma_form/validators.py
caluma/caluma_workflow/api.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/__snapshots__/test_work_item.ambr
caluma/caluma_workflow/tests/test_case.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/conftest.py
caluma/utils.py
docs/interfaces.md

Initial python api for caluma_form

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py
docs/validation.md

Introduce debug transforms, which allow users to take a look into
values being processed within JEXL. This is intended for people who are
configuring forms, workflows etc and need to debug their expressions.
This is my proposal to fix #1248. Will need a corresponding implementation in [ember-caluma](https://github.com/projectcaluma/ember-caluma) as well.

feat(jexl): debug transforms

---

CHANGELOG.md
caluma/caluma_metadata.py

* Handle table_questions ([`33d303c`](https://github.com/projectcaluma/caluma/commit/33d303c7427c88f9dfcde06e9828960e2d9ee795))
* Set default answers when creating new documents ([`d9c2b2e`](https://github.com/projectcaluma/caluma/commit/d9c2b2e2d49db2021e6e066d8a853f309310327b))
* Implement default_answers ([`e3dae80`](https://github.com/projectcaluma/caluma/commit/e3dae80bbe50a45051bdd826773c13eb32d582fb))
* Implement save_document form api ([`ffb422d`](https://github.com/projectcaluma/caluma/commit/ffb422d8e4ff6a146cf631a3b7f86f261ce195a7))
* Debug transforms ([`fbc5cd6`](https://github.com/projectcaluma/caluma/commit/fbc5cd663e1893770a5c2a07e59e2abf7f2b14b6))
* Useful __repr__ for most models ([`e6186cc`](https://github.com/projectcaluma/caluma/commit/e6186cc243e7d498918248fd814052db3c …

chore(release): prepare release v6.7.0

---

caluma/caluma_data_source/data_source_handlers.py
caluma/caluma_data_source/data_sources.py
caluma/caluma_data_source/schema.py
caluma/caluma_data_source/tests/data_sources.py
caluma/caluma_form/schema.py
docs/extending.md

BREAKING CHANGE: Pass the `user` to the `get_data` method of a data source instead of the whole `info` object since we don't have an info object when calling the python API.
Before:
```python
class CustomDataSource(BaseDataSource):
info = 'User choices from "someapi"'
@data_source_cache(timeout=3600)
def get_data(self, info):
response = requests.get(
f"https://someapi/?user={info.context.user.username}"
)
return [result["value"] for result in response.json()["results"]]
```
After:
```python
class CustomDataSource(BaseDataSource):
info = 'User choices from "someapi"'
@data_source_cache(timeout=3600)
def get_data(self, user):
response = requests.get(f"https://someapi/?user={user.username}")
return [result["value"] for result in response.json()["results"]]
```
This fixes the …

fix(dynamic question)!: pass user instead of info object to data source

---

.reuse/dep5
.travis.yml
CONTRIBUTING.md
Dockerfile
docker-compose.override.yml
requirements-all.txt
requirements-dev.txt
setup.cfg
setup.py

Explicitly declare install_requires instead of copying requirements.txt.
The setup.py needs looser requirements to ease package installation.
This has been an issue before, when caluma installed as a package, but
with the upcoming pip resolver downstream projects will break.
Add a separate travis build for the package.
Resolves #1271

chore: separate version pinning for install_requires

---

caluma/caluma_core/models.py

The `__str__()` method, according to python, MUST return a string.
The UUIDModel's `id` field is (not surprisingly) an UUID, and thus
must be converted. Otherwise, this will break string formatting, for example.

fix(api): __str__() should return string

---

caluma/caluma_form/migrations/0038_remove_table_answer_value.py
caluma/caluma_form/validators.py

This is another regression of 445741333fd77494bd323078c70d3717ad54135a. Before that commit, the value was saved on table answers. This caused problems when validating table answers that were created before that change since they had a string value which caluma tried to validate as documents.

fix(form): fix validation of table questions

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py
caluma/caluma_form/jexl.py
caluma/caluma_form/signals.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_answer.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/tests/test_question.py
caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py
caluma/caluma_workflow/jexl.py
docs/calculated-questions.md

This fixes a regression, when table questions are referenced that haven't been answered, so no row document is available. In this case the jexl failed because no field exists for such a question.
Thus we separate the extractors and extract the mapby arguments only where need, that is to determine the calc dependents.
Theoretically it would still be correct to treat the arguments as fields too (if the subject is an answer transform), but then we would need a way to distinguish between actually missing questions (don't exist in the form but are referenced in the jexl) and missing table answers (that are "optional" because a table doesn't necessarily need to have rows).
With the separate extractor we could do that, but there is currently no need for it during regular validation steps.

fix(jexl): separate extractor for mapby arguments

---

caluma/caluma_core/events.py
caluma/caluma_workflow/tests/test_events.py
docs/events.md

This allows us to control (on a per receiver basis) whether an exception in the receiver will cause an exception in the current transaction and therefore rollback said transaction.

feat(events): add argument to on decorator to raise exceptions in the receiver

---

caluma/caluma_core/management/commands/dump_caluma_config.py
caluma/caluma_core/tests/test_dump_caluma.py
caluma/caluma_form/tests/test_jexl.py
caluma/conftest.py
docs/commands.md

Dump an entire form as django fixtures using `./manage.py dump_caluma --model caluma_form.Form my-form-slug`.
This command lives in core so it can extended to other design-time aspects such as workflows, questions etc.
`load_caluma` is not necessary as the built-in `loaddata` does this already.
Partially addresses #1359

feat: dump_caluma command for entire forms

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py
caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_question.py

Change analyzer baseclass to include array literals when walking AST.
Previously the ValidatingAnalyzer would not walk Array or ObjectLiterals, thus not reaching nested AST nodes.

fix: use homebrew jexl analyzer for question extraction

---

CHANGELOG.md
caluma/caluma_metadata.py

* **form:** Add python API and command for copying forms ([`7620eec`](https://github.com/projectcaluma/caluma/commit/7620eec898b70dd641b758f0f4e09c6d3bdbacf8))
* **jexl:** Add min, max, sum, round transforms ([`beb714a`](https://github.com/projectcaluma/caluma/commit/beb714ad3c95ea4d32ef81ede84c023ed635511c))
* Dump_caluma command for entire forms ([#1367](https://github.com/projectcaluma/caluma/issues/1367)) ([`20b2a79`](https://github.com/projectcaluma/caluma/commit/20b2a79fea22f2b197d5f0238b33089ce063cde5))
* Use homebrew jexl analyzer for question extraction ([`a81c089`](https://github.com/projectcaluma/caluma/commit/a81c0898a6f5e9d847133bdf4700ad75c228a925))
* **form:** Don't validate calculated answer ([`014a804`](https://github.com/projectcaluma/caluma/commit/014a80434988d121f5cd92b …

chore(release): v7.7.0

---

caluma/caluma_core/relay.py
caluma/caluma_core/tests/test_relay.py
caluma/caluma_form/tests/test_form.py

We need to validate the extracted type in `extract_global_id()`, as it
may lead to errors when passing a valid slug, that's also valid base64,
and happens to contain a colon.
Instead of naively decoding and returning an invalid (type, identifier)
pair, validate the type's name and behave correctly in those cases.

fix: extract_global_id should not be too eager in decoding

---

caluma/caluma_core/filters.py
caluma/caluma_core/tests/test_search_filter.py

Using the search filter in the filter collection resulted in an error where the filter did not have a model. This was caused because the
class method `filterset.get_filters()` was used instead of the properly initialized `filterset.filters` where the model was properly set.

fix(filters): fix search filter when used in collection

---

caluma/caluma_form/serializers.py
caluma/caluma_workflow/serializers.py

The DRF documentation shows the fields list to be a list, not a
tuple. When analyzing the code using MyPy, it assumes that an N-tuple
is sort of a type, and changing the type to an N+X-tuple in a subclass
is therefore a type validation (which I sort of agree with).
Therefore, let's use lists instead.

refactor: fields list should be list, not tuple

---

caluma/caluma_form/storage_clients.py
caluma/caluma_form/tests/test_minio.py

Minio in the newest version changed some API sturucture. Mainly, the
exception NoSuchBucket does not exist anymore, and is now part of the
S3Error exception.
While we're at it, also remove some duplicate code and move it into
a decorator (Any other place would imply more boilerplate).

fix(dependencies): update minio client to adjust for changed exceptions

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py
caluma/caluma_form/tests/test_question.py

This extends the mapby transform to accept multiple keys as argument
which then returns an array instead of the single value. This will
result in nested arrays which is why we added a stringify transform that
converts such a collection into a string to be used in comparisons.

feat(jexl): improve mapby and add stringify transform

---

caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/caluma_workflow/utils.py

When a work item is created from a workflow event (triggered via task),
we used bulk_create_with_history(), which doesn't send signals. Thus,
the `set_name_and_description` signal was not triggered, leaving us with
anonymous work items.

fix(workflow): correctly set workitem name from task

---

caluma/caluma_core/conftest.py
caluma/caluma_core/health_checks.py
caluma/caluma_core/tests/__snapshots__/test_health_checks.ambr
caluma/caluma_core/tests/test_health_checks.py
caluma/caluma_core/urls.py
caluma/caluma_core/views.py
caluma/settings/caluma.py
caluma/settings/django.py
caluma/urls.py
docs/configuration.md
docs/django-apps.md
docs/healthz.md
requirements.txt
setup.cfg
setup.py

Introduce /healthz endpoint to allow for readiness checks in Kubernetes.
Use Django-Watchman to execute checks (already includes checks for caches and databases)
and is extended with additional checks for minio, db models and db migrations.
Resolves #1137

feat: health endpoint

---

caluma/caluma_form/serializers.py

This makes sure that the `created_by_*` and `modified_by_*` properties
are set correctly.

fix(document): pass current user to copy document function

---

caluma/caluma_core/tests/test_visibility.py
caluma/caluma_core/visibilities.py

This commit fixes a regression that was first introduced with
cf1f91dd88480d3ae206fc790db49c649f91ccc3 and then fixed with
2c195534db89a5622b62ae93a56ad5fe9ffec2c4, but then re-introduced with
b85ae9676fb4245a6d2817f376c23c495db0c146.
This time I was able to reproduce it and this commit contains a test.
Related issues and PRs:
* #569
* #598
* #599
* #841

fix(caluma): fix regression for union visibilities

---

caluma/caluma_form/models.py
caluma/caluma_form/schema.py
caluma/caluma_form/tests/__snapshots__/test_document.ambr
caluma/caluma_form/tests/test_document.py
caluma/tests/__snapshots__/test_schema.ambr

This commit adds a new field `selected_option` to `StringAnswer`,
holding the selected option for (dynamic) choice-questions and a new
connection `selected_options` to `ListAnswer` for (dynamic)
multiple-choice-questions.
Closes #1301

feat: make selected option(s) accessible from answers

---

uwsgi.ini

UWSGI has a buffer of 4096 bytes by default, in which all request headers
must fit. If a user has particularly many roles/groups in their JWT token,
this limit is exceeded. UWSGI will then abort the request, and the reverse
proxy in front will respond with an error such as HTTP/502.

fix: extend uwsgi buffer

---

caluma/caluma_core/jexl.py
caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py
docs/validation.md

This allows the user to write reusable JEXLs using answer transforms that don't necessarily resolve to a question in a certain form context.
https://github.com/projectcaluma/ember-caluma/pull/1435

feat(jexl): allow optional answer transforms with default value

---

caluma/caluma_core/serializers.py

By updating ModelSerializer.serializer_field_mapping, we implicitly
update the parent class' attribute, instead of just setting it on "our"
ModelSerializer.

fix(serializers): do not implicitly monkeypatch rest framework

---

caluma/caluma_user/views.py
caluma/settings/caluma.py
docs/configuration.md
docs/extending.md

Allow users to provide a custom user factory to build the OIDCUser
object. This enables us to extend it and make it compatible with
other OIDC RP apps (such as Emeis, Alexandria etc).

feat(config): introduce configurable user factory

---

caluma/caluma_core/events.py
caluma/caluma_form/signals.py
docs/events.md

The event filter decorator allows you to check against some predicate
functions before executing an event handler. This simplifies the handlers
by removing boilerplate code and allowing them to concentrate on the
work at hand.

feat(signals): introduce event filter

---

caluma/settings/django.py
docs/extending.md

With the current django configurations exposed, it was not possible to deploy and use caluma in a CORS scenario. 
With this change more CORS header configurations are exposed via environment variables. Furthermore it enhances the django default values with some caluma required stuff like the language header.

feat: Expose more CORS related configurations via environment variables

---

caluma/caluma_core/permissions.py
caluma/caluma_core/tests/test_mutation_params.py
caluma/caluma_core/tests/test_permissions.py
caluma/schema.py

When usig an invalid mutation class in the permission classes, things
might work unexpectedly, even though not actually being correct.
This validation checks that your permission classes actually
use a mutation that exists in the system.
fixes #1614

feat(config): validate permission decorators

---

requirements.txt
setup.py

This should make Caluma releaseable again

chore: bump pyjexl to 0.3.0

---

.github/workflows/ghcr.yml

* Builds on the `main` branch will push a tag named `dev`
* Builds on releases (tags) will push a tag named `latest`
as well as a tag with the proper version number.
Thus, `latest` should always be the last-properly-released version,
and if you need tha latest development version, you can use the `dev`
docker tag instead.

chore(build): cleanup docker build process

---

CHANGELOG.md
caluma/caluma_metadata.py

Contains some additional stuff (as discussed) next to the version bump:
* Builds on the `main` branch will push a tag named `dev`
* Builds on releases (tags) will push a tag named `latest`
as well as a tag with the proper version number.
Thus, `latest` should always be the last-properly-released version,
and if you need tha latest development version, you can use the `dev`
docker tag instead.

Release 7.14

---

caluma/caluma_workflow/serializers.py

Those status fields are only used for the type system, but not as actual
input types. Thus, they're never actually instantiated

fix: coverage in new status fields

---

caluma/caluma_form/models.py

Currently `document.copy` fails when a calculated question is configured in the form because the signal already creates an answer for that question.

fix(form): update or create answers when copying to a new document

---

.reuse/dep5

I intentionally didn't update the copyright year because I assumed that we use the year of the initial publication as stated here: https://reuse.software/faq/#years-copyright

chore(reuse): update reuse config

---

caluma/caluma_workflow/events.py

The argument `providing_args` for django signals was deprecated in 3.1: https://docs.djangoproject.com/en/4.0/releases/3.1/#id2

chore(events): remove deprecated providing_args argument for signals

---

Dockerfile

This shrinks our image by exactly 50% (1.08GB before, 540MB after)

chore(docker): use slim image

---

caluma/caluma_analytics/tests/test_table.py
caluma/caluma_core/pagination.py
caluma/caluma_core/relay.py
caluma/caluma_core/types.py
caluma/caluma_form/tests/__snapshots__/test_answer.ambr
caluma/caluma_form/tests/test_answer.py
caluma/caluma_form/tests/test_document.py
requirements.txt
setup.py

Closes #1683
`connection_from_list` and `connection_from_list_splice` are deprecated in favor of `connection_from_array` and `connection_from_array_splice`. Since we override it this is not really necessary but it makes sure that we don't use deprecated functions when https://github.com/graphql-python/graphql-relay-py/issues/12 is fixed.
This also fixes old imports that are now exposed in the top level of `graphql_relay`.

chore(deps): update graphql-relay

---

caluma/caluma_workflow/tests/test_work_item.py
caluma/caluma_workflow/utils.py

Work items should only be created if they don't exist yet or if the task allows multiple instances. This makes sure that we don't have accidental duplicate of work items. This intentionally doesn't use `get_or_create` to avoid the creation of an obsolete documents since django doesn't support lazy defaults.
Closes #1512
*Disclaimer: This is basically copy paste of #1659 with a refactoring to use a preliminary query instead of `get_or_create` to avoid obsolete documents and deadline computations.*
Closes #1659

feat(workflow): only create work item if they don't exist yet

---

caluma/caluma_analytics/pivot_table.py
caluma/caluma_analytics/schema.py
caluma/caluma_analytics/simple_table.py
caluma/caluma_analytics/tests/test_pivot_table.py
caluma/tests/__snapshots__/test_schema.ambr

Add a summary output to pivot tables. This gives the same aggregates,
but without grouping, thus applying the aggregates over all results.
Note: Stacks on top of #1719 and must be rebased before merge.

Feat: analytics summary

---

caluma/caluma_form/tests/test_minio.py

We should avoid having this external dependency, but for now, it
servers it's purpose (unless it's down, as of right now).
Since the test is not verifying an overly critical behaviour, we
allow it to fail if the external dependency is not available.
See https://github.com/chromium/badssl.com/issues/500

test: allow minio cert checks to fail if badssl.com is down

---

caluma/settings/django.py

Django now wants to have DEFAULT_AUTO_FIELD as a setting. This doesn't
need to be configurable, so we just set it to the value it has always
been implicitly.

chore: set default auto field in settings

---

caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/events.py
caluma/caluma_workflow/schema.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_reopen_case.py
caluma/tests/__snapshots__/test_schema.ambr

Adds the ability to reopen a previously `completed` case.
During re-opening of a case the ID of the case as well as an array of `work-items` have to be supplied.
- Case status has to be `STATUS_COMPLETED` or `STATUS_CANCELED`. Suspended cases can not be reopend.
- A case can not be a child case
- Only work items at the end of a branch can be re-opened
- Only work items belonging to the case that is being re-opened can be re-opened

Feat: reopen case

---

caluma/caluma_workflow/schema.py

`fields: ["id"]` is type definition but was (I think) intended to be a property definition. However, since that field is already defined in the `Input` this isn't necessary.

chore(schema): remove obsolete fields type definition

---

pyproject.toml

`graphene-django` uses a removed function `format_error` from
`graphql-core` but accepts the version in which it was removed as a
valid dependency. This commit makes sure we only use working versions of
`graphql-core`.
https://github.com/graphql-python/graphql-core/commit/09ff14f68bdce1e9cd71decc871fd38274b01971

fix(deps): lock graphql-core to 3.1.x to avoid import error

---

caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/events.py

BREAKING CHANGE:
The following deprecated events were removed:
- `created_work_item`
- `completed_work_item`
- `skipped_work_item`
- `suspended_work_item`
- `resumed_work_item`
- `completed_case`
- `created_case`
- `suspended_case`
- `resumed_case`
- `canceled_work_item`
- `cancelled_work_item`
- `canceled_case`
- `cancelled_case`

feat(events): cleanup deprecated events

---

caluma/caluma_analytics/filters.py
caluma/caluma_analytics/schema.py
caluma/caluma_core/filters.py
caluma/caluma_core/forms.py
caluma/caluma_core/ordering.py
caluma/caluma_form/filters.py
caluma/caluma_form/schema.py
caluma/caluma_form/tests/test_form.py
caluma/caluma_workflow/filters.py
caluma/caluma_workflow/schema.py
caluma/tests/__snapshots__/test_schema.ambr

BREAKING CHANGE: This removes various orderings that do not make sense
and were not used:
- On all connections:
- `created_by_user`
- `created_by_group`
- `modified_by_user`
- `modified_by_group`
- `Answer`
- `document`
- `file`
- `Document`
- `source`
The following ordering attributes were added because they make sense:
- `Case`
- `created_at`
- `modified_at`
- `Flow`
- `created_at`
- `modified_at`
- `Task`
- `created_at`
- `modified_at`
- `Workflow`
- `created_at`
- `modified_at`
- `AnalyticsField`
- `created_at`
- `modified_at`
- `alias`
- `DynamicOption`
- `created_at`
- `modified_at`
- `slug`
- `label`
- `question`
- `Flow`
- `created_at`
- `modified_at`
- `task`

feat(ordering): remove unused ordering attributes and add missing 

---

caluma/caluma_analytics/tests/test_starting_objects.py

This test checks the month of a creation date which just changed some days ago. By freezing the date for the test this won't be an issue in the future.

test(analytics): fix flaky test using creation date

---

pyproject.toml

When an application uses Caluma as a Django package, it is often very
beneficial to be able to reuse Caluma's fixtures. In fact, we do have
projects that do depend on Caluma's conftest. So, this should be built
into the package.

fix(build): conftest should be in generated package

---

caluma/caluma_form/structure.py

This allows prefetching the answer documents (table rows) to avoid DB
hits when generating the form structure.

fix(form): use potentially prefetched answer document set for table rows

---

caluma/caluma_workflow/filters.py
caluma/tests/__snapshots__/test_schema.ambr

remove non exsisting ordering keys for work item and
task, fix relational ordering keys for case and work item
removes allow_all_forms and is_published from work item and task
rename is_archived on work item to task__is_archived
append workflow__ to keys on case which are from workflow relation

fix(workflow): remove and fix ordering keys

---

caluma/caluma_form/storage_clients.py
caluma/caluma_form/tests/test_minio.py

When an object in Minio cannot be `stat`ed, this should not be logged
as an error: It may be quite a normal result, for example if a file has
not been uploaded yet, and Caluma for some reason wants to check it.
Therefore, degrading the log message from "error" to "warning".
Also, for debugging reasons, we're adding the object name to the
log message: Without it, we're getting errors in the log and have no
chance of figuring out why it happened.

fix(log): minio stat errors shouldn't be errors

---

caluma/caluma_analytics/simple_table.py
caluma/caluma_analytics/tests/__snapshots__/test_starting_objects.ambr

Identifier fields cannot be sorted or have string functions applied to them in a
meaningful manner - nobody should require the "max" of an UUID for example.
Also, Meta fields (not their contents!) cannot have any useful aggregate
function applied to them either

fix(analytics): provide more correct supported functions in analytics

---

caluma/caluma_form/historical_schema.py
caluma/caluma_form/migrations/0046_file_answer_reverse_keys.py
caluma/caluma_form/tests/test_migrate_to_multiple_files.py

We cannot handle historical answers and "current" answers the same way
when migrating their files: Historical answer's files need to be fetched
from history as well, and their history needs to be updated also.
When fetching the historical files of an answer, we need to fetch
exactly the files that were there at the given date/time, not all that
have ever been created (but may have been deleted in the mean time)
This supersedes #1839

fix(form): fix migration problem with historicalanswer

---

caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/schema.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/__snapshots__/test_workflow.ambr
caluma/caluma_workflow/tests/test_reopen_case.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/caluma_workflow/tests/test_workflow.py
caluma/tests/__snapshots__/test_schema.ambr

- Add `is_redoable` property to work item schema
- Allow empty `next` on flows if `redoable` is given
- Allow reopening child cases if the parent work item is ready
- Don't create a new work item after completing a redone work item if there are succeeding work items in status redo

Redo work item / reopen case improvements

---

caluma/caluma_workflow/serializers.py

BREAKING CHANGE: The `saveWorkItem` mutation doesn't emit `pre_create_work_item` `post_create_work_item` anymore since this is not the expected behaviour.

fix(events): don't emit create work item events when updating

---

caluma/caluma_data_source/data_source_handlers.py
caluma/caluma_data_source/data_sources.py
caluma/caluma_data_source/schema.py
caluma/caluma_data_source/tests/__snapshots__/test_data_source.ambr
caluma/caluma_data_source/tests/data_sources.py
caluma/caluma_data_source/tests/test_data_source.py
caluma/caluma_data_source/utils.py
caluma/caluma_form/domain_logic.py
caluma/caluma_form/schema.py
caluma/caluma_form/serializers.py
caluma/caluma_form/tests/__snapshots__/test_dynamic.ambr
caluma/caluma_form/tests/test_dynamic.py
caluma/caluma_form/validators.py
caluma/tests/__snapshots__/test_schema.ambr

https://github.com/projectcaluma/ember-caluma/pull/2205
This implements further context for data sources since they currently only have the `user` as context. We added the `question` and a JSON object `context` as new arguments for the data source `get_data` method. This way we have much more possibilities when writing data sources.

feat(data_source): add question and context arguments for data sources

---

caluma/caluma_analytics/schema.py
caluma/caluma_analytics/sql.py
caluma/caluma_analytics/tests/__snapshots__/test_simple_table.ambr
caluma/caluma_analytics/tests/test_simple_table.py

Analytics uses generated SQL from the visibility layer of the application. However, only the part after the WHERE is actually used. Now if a visibility layer adds expressions that affect the FROM bit of an SQL statement, and these expressions contain query parameters, we have too many parameters in for the remaining SQL fragment.
Those parameters need to be discarded, as we don't use the SQL that came along with them.
Then, as a drive-by fix: It doesn't make sense to extract a summary row for simple tables - there is nothing to summarize in a meaningful way. Fixe a crash where the frontend would request a summary nonetheless.

Fix analytics sql generation

---

caluma/caluma_user/models.py
caluma/caluma_user/tests/test_views.py
caluma/settings/caluma.py

When authentication happens with a "service user" instead of a regular user, we may not get a username. However, we can now configure Caluma to use the client ID as username instead.
This is optional to ensure that the behaviour is intended, and no "wrong" fallback happens in case the username claim was just configured incorrectly.

feat: allow using client id as user for client-secret auth

---

caluma/settings/django.py

When enabling dev mode, we should not rely on all the dev dependencies being installed. Instead, try to see if `django-extensions` is even installed, and only add it to the `INSTALLED_APPS` list if it is.
Fixes #1932

fix: do not crash when django-extensions is missing

---

caluma/caluma_analytics/simple_table.py
caluma/caluma_analytics/sql.py
caluma/caluma_analytics/tests/__snapshots__/test_run_analytics_cmdline.ambr
caluma/caluma_analytics/tests/__snapshots__/test_starting_objects.ambr
caluma/caluma_analytics/tests/__snapshots__/test_table.ambr
caluma/caluma_analytics/tests/test_form_field_extraction.py

Displaying form information for subforms is broken. Since there is no pressing use case for this anyway, this commit disables it alltogether.

fix(analytics): fix form identifier; disable subform form

---

caluma/caluma_analytics/tests/test_migrate_form_slugs.py
caluma/caluma_form/migrations/0047_recalculate_calc_answers.py
caluma/caluma_form/signals.py
caluma/caluma_form/tests/__snapshots__/test_filter_by_answer.ambr
caluma/caluma_form/tests/test_filter_by_answer.py
caluma/caluma_form/tests/test_migrate_to_multiple_files.py
caluma/caluma_form/tests/test_migration.py
caluma/caluma_workflow/tests/test_migrations.py
caluma/conftest.py

* fix: fix calc answer evaluation when adding new table rows
* chore(tests): do not use nested documents
In the past we've had some misconceptions about document structure and
introduced nested documents. This commit cleansup a remnant of this
mistake, that was forgotten back then.
* chore(tests): migrate to current state after migration tests
This commit introduces a `post_migrate_to_current_state`-fixture to properly
cleanup after our migration tests.

fix: fix calc answer evaluation when adding new table rows

---

CHANGELOG.md
pyproject.toml

* **form:** Fix validation in document validity graph ([`6b859fa`](https://github.com/projectcaluma/caluma/commit/6b859fa1f76762a8fcfadff7f1010ec4b17d02f4))

chore(release): v8.0.0-beta.26

---

caluma/caluma_form/filters.py
caluma/caluma_form/tests/test_search_answers.py
pyproject.toml

This commit implements searching for exact word combinations if words are enclosed in quotations. If the amount of quotation marks is uneven, we implicitly add an ending quotation at the end of the search string.
Closes #1927

feat(filters): Support word combinations in SearchAnswersFilter

---

caluma/caluma_workflow/filters.py
caluma/caluma_workflow/tests/test_date_filters.py
caluma/tests/__snapshots__/test_schema.ambr

Work items can now be filtered by their deadline by comparing them to a given date ("show work items with deadline before date X" or "after date X"), helping you find overdue work items.

feat(filters): add useful deadline filters to workitems

---

.github/workflows/ghcr.yml
.github/workflows/tests.yml
Dockerfile
docker-compose.override.yml

- Install `wait-for-it` from debian packages
- Use dedicated run cache for apt commands
- Reorder dockerfile to improve caching
- Use docker github actions for publishing the image. **NEW:** a release `v8.2.1` will produce / update the following image tags:
- `latest`
- `8.2.1`
- `8.2`
- `8`
Closes #1972

Improve docker image

---

caluma/caluma_form/schema.py
caluma/caluma_form/tests/test_document.py
caluma/caluma_form/validators.py
caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/caluma_workflow/validators.py
caluma/tests/__snapshots__/test_schema.ambr

Provide context information such as validation context or data source
context to the WorkItemValidator. This information can for example be
relevant for validating dynamic questions in the document validator.

fix(workflow): provide context to WorkItemValidator

---

caluma/caluma_user/models.py
caluma/caluma_user/tests/test_views.py
caluma/caluma_user/views.py
caluma/settings/caluma.py
pyproject.toml

For OIDC-auth it's not necessary to have a fallback to the introspect endpoint, so this commit drops it. For this to work, make sure to include the `openid`-scope in the request.
BREAKING CHANGE: setting the `OIDC_INTROSPECT_*` and `OIDC_CLIENT_AS_USERNAME` env vars is obsolete now. Auth now only calls the userinfo endpoint without any fallback to the introspect endpoint. This will possibly have an impact on the `username` property of the user object. If your extensions depend on that property, please update them if necessary.
Additionally, all requests sent to Caluma must include the `openid`-scope.

feat(auth)!: only use userinfo for auth (drop introspect)

---

caluma/caluma_form/jexl.py

Currently, starting a new case fails if any of the JEXL evaluations in a form return a `ZeroDivisionError` in the signal layer.
Add `ValueError` and `ZeroDivisionError` to catch block around JEXL evaluation in signal layer.
We evaluate JEXL expressions greedily in the signal layer, but do so without raising:
https://github.com/projectcaluma/caluma/blob/7125c6a801f76d95ea30b2e90aff3d16d307a6b3/caluma/caluma_form/signals.py#L104
However, in the `jexl.update` function we only catch `TypeError`:
https://github.com/projectcaluma/caluma/blob/7125c6a801f76d95ea30b2e90aff3d16d307a6b3/caluma/caluma_form/jexl.py#L201
This is also not consistent with the catch block here, where we catch `TypeError`, `ValueError` and `ZeroDivisionError`:
https://github.com/projectcaluma/caluma/blob/7125c6a801f76d95ea3 …

fix: catch ValueError and ZeroDivision errors on early jexl evaluation

---

caluma/caluma_form/factories.py
caluma/caluma_form/models.py
caluma/caluma_form/schema.py
caluma/caluma_form/serializers.py
caluma/tests/__snapshots__/test_schema.ambr

This will be used in the frontend to toggle the visibility of validation messages when submitting forms with action buttons:
https://github.com/projectcaluma/ember-caluma/pull/2488

feat: add show_validation property for action buttons

---

caluma/caluma_core/health_checks.py
caluma/caluma_form/storage_clients.py
caluma/caluma_form/tests/test_minio.py

As part of the health-check routines, a file is removed in minio and afterwards it's asserted that the file is gone. This call to `Minio.stat_object()` led to a warning being issued during every health-check iteration like the following:
```
Minio error, cannot stat object 'healthz_tmp-object_{UUID}': NoSuchKey
```
This commit extends `Minio.stat_object()`, so that issuing of the log-warning can be suppressed by profiding the argument `warn_missing=False`. Default behaviour doesn't change and will still issue this warning.

fix(healthz): do not warn about expected events

---

caluma/caluma_core/conftest.py
caluma/caluma_core/health_checks.py
caluma/caluma_core/tests/__snapshots__/test_health_checks.ambr
caluma/caluma_core/tests/test_health_checks.py
caluma/settings/django.py

This commit removes writing to the DB and MinIO as part of the health-checks. Additionally also DB-permissions, etc are not checked anymore. Those checks did not provide any real value, but resulted in unnecessary load on the systems.

feat(healthz): overhaul health-checks for them to be less intrusive

---

caluma/caluma_form/models.py
caluma/caluma_form/tests/test_document.py

Adds a `flat_answer_map` property to a document which can be used in the same was as we do it in `ember_caluma`.

feat: implement flat_answer_map

---

caluma/caluma_workflow/domain_logic.py

This prevents untouched fields of the case model which were updated in a event to be overwritten with an old value.

fix: only save updated fields in post_complete case logic

---

caluma/caluma_workflow/filters.py
caluma/tests/__snapshots__/test_schema.ambr

BREAKING CHANGE: you now must use the `ids` filter instead
This should go in before the 10.0.0 release

chore: drop deprecated id filter on cases filterset

---

caluma/caluma_user/views.py
caluma/settings/caluma.py

This should avoid overly comples GraphQL queries which might overload the backend. Note: We do not yet have experience with the exact useful value of this settings, so the default is zero (which implies the limit is disabled)
Edit: Ran some manual tests (It's hard to do automated tests for stuff like that). The setting works, but I'm still not sure what a reasonable limit would be. I assume it will be around 15-20 realistically

feat(settings): add setting to limit query depth

---

.gitlint

Our regex is alredy anchored, so the change it was warning about doesn't affect us

chore: fix gitlint config - remove warning about pending changes

---

CHANGELOG.md
caluma/caluma_core/conftest.py
caluma/caluma_core/health_checks.py
pyproject.toml

This yields a routing problem with reverse proxies. Now we're checking for the configured bucket, which makes more sense anyway.

fix: do not query for non-existent buckets in healthz

---

caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_jexl.py

This is convenient when you'd like to write a JEXL expression in a task form attached to some work item, that depends on the case's main documents' form.
Related PR in ember-caluma: https://github.com/projectcaluma/ember-caluma/pull/2703
Once we merge this, we should spend a minute to update the caluma docs: https://caluma.gitbook.io/caluma-docs/forms/validation#variables-available-for-evaluation

feat(jexl): add main_case_form to info object

---

caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_jexl.py

As suggested in https://github.com/projectcaluma/ember-caluma/pull/2703#discussion_r1579985434

feat(form): add more case info to jexl context

---

CODE_OF_CONDUCT.md

contact@caluma.io is not working anymore, and is a hassle to maintain. This replaces the address with my personal one for simplicity.

fix(code of conduct): contact mail address

---

caluma/caluma_form/structure.py

info.case.root should always be defined - when we're in the root case, it just resolves to the same value as info.case. This matches the way it is already implemented in ember-caluma.

fix(jexl): always add root info

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py

Needs https://github.com/projectcaluma/ember-caluma/pull/2784

feat(jexl): add length transform

---

CHANGELOG.md
pyproject.toml

* **jexl:** Add length transform ([`b4fbd99`](https://github.com/projectcaluma/caluma/commit/b4fbd997b866f82b3b65bcc0fb6e1237ca69e0df))
* **form:** Speed up copying of documents ([`fac7a98`](https://github.com/projectcaluma/caluma/commit/fac7a986de97cd8fb1a7d1f8444df8c83afeab3a))
* Add missing "is_hidden" to SaveOptionSerializer ([`ab63598`](https://github.com/projectcaluma/caluma/commit/ab63598d1051739eb3989d48d446e61e8d19568b))

chore(release): v10.4.0

---

caluma/utils.py

When an optional property is looked up, the default behaviour would be to just return None (in Graphene), but our code called `getattr()` without default param, causing the code to crash.

fix(visibilities): don't crash in the suppressable visibility resolver

---

.pre-commit-config.yaml
.reuse/dep5
caluma/caluma_core/exceptions.py
caluma/caluma_core/jexl.py
caluma/caluma_form/domain_logic.py
caluma/caluma_form/jexl.py
caluma/caluma_form/models.py
caluma/caluma_form/serializers.py
caluma/caluma_form/signals.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_complex_jexl.py
caluma/caluma_form/tests/test_data/complex_jexl_context.json
caluma/caluma_form/tests/test_document.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/tests/test_option.py
caluma/caluma_form/tests/test_question.py
caluma/caluma_form/tests/test_structure.py
caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/utils.py
caluma/caluma_form/validators.py
caluma/conftest.py

The new structure / jexl evaluator works a bit differently: Instead of
trying to replace evaluation contexts during recursive evaluation (for
example `is_hidden` checks), we now have a local JEXL runtime for each
field. Also, the JEXL expressions (or their results, rather) are heavily
cached and should speed things up significantly.
Regarding the test cases:
We're trying to keep the test cases' meaning 100% unchanged - the only
modifications currently are some improved assertion messages, so
debugging becomes easier, as well as refactoring some for better readability.
Some tests are extended, and some are now better documented, to cover
more aspects and explain in more detail what our assumptions and
expectations actually are.
BREAKING CHANGE: Code that uses the form jexl and / or …

refactor(forms): rewrite structure and jexl evaluator

---

caluma/caluma_form/validators.py

The new structure code has a strict policy of only doing weakrefs from child fields to their parents, to avoid circular dependencies and therefore causing GC leaks.
However the validation code had a situation where a child field was used while the (root) field went out of scope, therefore losing the form structure.
This is now fixed - the private utility method `_structure_field()` now returns the root field as well, even though it's not actually being used.
While we're at it, also raise a ConfigurationError if a field is missing in a form.

fix(jexl): fix crashes in form validation when validating options

---

caluma/caluma_form/domain_logic.py
caluma/caluma_form/tests/test_question.py
caluma/caluma_form/utils.py

This is now done by the structure's own fastloader, so we don't need to prefetch anymore. The FastLoader is also much easier to understand than the prefetch here.

refactor: drop prefetch_document()

---

caluma/caluma_form/factories.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/__snapshots__/test_document.ambr
caluma/caluma_form/tests/__snapshots__/test_question.ambr
caluma/caluma_form/tests/test_option.py
caluma/caluma_form/tests/test_structure.py

This allows reuse of the fastloader across multiple documents of a queryset, which will speed up things in list views for example

feat(forms): extend structure fastloader to support multiple documents

---

caluma/caluma_form/domain_logic.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_question.py
caluma/caluma_form/tests/test_structure.py

When calculating a field, we must take better care to update
the dependents, invalidate all the cached values, and ensure the
intermediate values are correctly used.
Rename `update_calc_dependents()` to `recalculate_dependents()`, because
there's a similarly-named function in caluma_form.utils that does
something else, which is confusing

Fix indirect calculations

---

.github/workflows/compatibility-tests.yml
.github/workflows/tests.yml

Python version 3.9 and PostgreSQL 12 are being deprecated. In their place, start testing with Python 3.13 and PostgreSQL 17

chore(ci): deprecate python and postgres versions

---

.github/workflows/tests.yml

I believe this version should be updated accordingly to https://github.com/projectcaluma/caluma/pull/2393

 chore(ci): update minimal python version in github actions

---

caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

Question options can have a JEXL to decide whether they're hidden or not. Most of them however do not use this feature, and for those, loading the full document into memory just to evaluate their (non-existing) `is_hidden` expression is just a waste of resources/time.

fix(perf): don't load full document in memory if not needed for options

---

caluma/caluma_data_source/data_sources.py
caluma/caluma_data_source/tests/data_sources.py
caluma/caluma_form/models.py
caluma/caluma_form/tests/test_answer.py
caluma/caluma_form/tests/test_document.py

Add a on_copy feature for datasources to optionally alter the dynamic option answer value and label

feat(copy): adds on_copy to datasources to alter dynamic values

---

caluma/caluma_form/models.py
caluma/caluma_form/tests/test_document.py

In my previous PR https://github.com/projectcaluma/caluma/pull/2378 a new feature `on_copy` was introduced on an Answer, in order for a datasource to be able to change an answer value when a form gets copied (in case the answers change when copying a document, e.g. for dynamic answers in the form).
**Process of copying answers:**
- A document gets copied (main document to start with)
- Each answer in the document gets copied
- If an answer is a table answer, the AnswerDocument's for that table gets copied, recursing back to the document copy
**The problem with this setup:**
The order in which these answers are copied is depending on the recursive form structure, therefore an answer might get copied, before other dynamic answers are copied, and the on_copy process cannot complete …

fix(copy); change order of document-answer on_copy

---

caluma/caluma_core/models.py
caluma/caluma_workflow/tests/test_proxy_model_history.py

`django-simple-history` currently creates historical records for proxy
models as well instead of using the historical records of the base
model. This issue is tracked in https://github.com/jazzband/django-simple-history/issues/544 but
doesn't seem to get any attention currently which is why we applied the
workaround from this comment:
https://github.com/jazzband/django-simple-history/issues/544#issuecomment-1538615799
This will make sure that changes on a proxy model will be tracked in the
historical records of the base model.
Resolves #2421

fix(history): make history aware of potential proxy models
