projectcaluma/caluma

requirements.txt

This way pyup will inform us on new versions and potential graphql changes

Pin graphql dependency

---

caluma/form/models.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/tests/snapshots/snap_test_schema.py

Split number type into integer and float

---

caluma/filters.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_form.py
caluma/form/tests/test_question.py
caluma/tests/test_schema.py
requirements.txt

#26 needs to be merged first
Removed generic schema query tests as the tests got too custom.

 Add filter support to question and form connection 

---

caluma/form/models.py
caluma/mutation.py
caluma/tests/__init__.py

Use enum types in mutation as well

---

caluma/mutation.py
caluma/tests/test_mutation.py

Add test to cover all different paths

Use django api to get field in convert_serializer_field_to_enum

---

caluma/document/filters.py
caluma/document/schema.py
caluma/document/tests/snapshots/snap_test_document.py
caluma/document/tests/test_document.py
caluma/filters.py
caluma/form/filters.py
caluma/form/schema.py
caluma/form/tests/test_question.py
caluma/workflow/filters.py
caluma/workflow/schema.py

Fixes #46 
Define only_fields specifically for each object type to not accidentally allow access through reverse relations.

Add search filter functionality

---

caluma/form/filters.py
caluma/form/tests/test_question.py

Add excludeFormQuestions to question mutation

---

caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/test_form.py
caluma/serializers.py

Allow blank of not required localized fields

---

caluma/filters.py
caluma/form/filters.py
caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_question.py
caluma/mutation.py
caluma/schema.py
caluma/tests/test_schema.py

Fixes #40  
Currently there is no configuration options for each type which will be added in future PR.

Introduce graphql types for each question type

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/serializers.py
caluma/workflow/tests/snapshots/snap_test_workflow_specification.py
caluma/workflow/tests/test_workflow_specification.py

Fixes #65 
For this to work next jexl needs to be required.

Verify next jexl on add of flow instead of publish

---

caluma/document/serializers.py
caluma/form/models.py

Optional question configuration options need to be nullable

---

.pre-commit-config.yaml
README.md

Introduce pre-commit hooks

---

caluma/form/jexl.py
caluma/form/schema.py
caluma/form/serializers.py
caluma/tests/snapshots/snap_test_schema.py

Introduce scalar type for isHidden and isRequired question fields

---

caluma/settings.py
caluma/urls.py
caluma/user/apps.py
caluma/user/middleware.py
caluma/user/models.py
caluma/user/tests/test_middleware.py
pytest.ini
requirements-dev.txt
requirements.txt

Add open id connect authentication middleware

---

caluma/form/filters.py
caluma/tests/snapshots/snap_test_schema.py

Add id filter on allDocuments graph

---

caluma/conftest.py
caluma/form/schema.py
caluma/form/tests/test_document.py
caluma/settings.py
caluma/tests/test_mutation.py
caluma/tests/test_visibility.py
caluma/types.py
caluma/user/models.py
caluma/user/tests/test_visibility.py
caluma/user/visibilities.py
caluma/visibilities.py

Fixes #104 
Documentation will be addressed with #103

Add visibility extension layer

---

caluma/mutation.py
caluma/permissions.py
caluma/settings.py
caluma/tests/test_mutation.py
caluma/tests/test_permissions.py
caluma/user/permissions.py
caluma/user/tests/test_permissions.py

Add permission layer for mutation

---

caluma/conftest.py
caluma/user/middleware.py
caluma/user/models.py

This allows extensions points to implement custom permissions and visibilities based on token.

Allow access to token and decoded_token in user object

---

caluma/core/filters.py
caluma/form/filters.py
caluma/form/tests/snapshots/snap_test_form.py
caluma/form/tests/test_form.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py

Fixes #137 
For each connection an enum is created with all possibilities of ordering with a descending and ascending version.

Add orderBy argument to all connections

---

docker-compose.yml

For this database needs to be accessible through exposed port

Add support to run pytest locally

---

CONTRIBUTING.md
README.md
caluma/core/permissions.py
caluma/extensions/permissions.py
caluma/extensions/visibility.py
docker-compose.yml

Fixes #103 
This includes how to configure Caluma.

Add documentation on how to get started and contribution

---

README.md
caluma/conftest.py
caluma/user/permissions.py
caluma/user/tests/test_permissions.py

Only allow mutating data that belongs to same group as current user.

Add CreatedByGroup permission class

---

requirements.txt

See https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

Define egg name for VCS dependencies as per specification

---

README.md
caluma/form/jexl.py
caluma/form/schema.py
caluma/form/validators.py

This allows is_required and is_hidden to be dependen on answers of other questions.

Add answer transform to question jexl

---

CONTRIBUTING.md
Dockerfile

This allows to install pip for user without having root.

Give docker user a home

---

requirements.txt

Obsolete as we moved to renovate

Remove pyup constraint

---

caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/test_document.py
caluma/form/validators.py

This uncovers a typo in validation method.

Add success for answers of question type text area

---

caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/test_form.py
caluma/form/tests/test_question.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
caluma/workflow/serializers.py
caluma/workflow/tests/test_task.py
caluma/workflow/tests/test_workflow.py

Fixes #199 
API user needs to have the ability to set publish and archive flag
to False so it doesn't make sense to have its own mutation for this.

Remove obsolete publish and archive mutations

---

caluma/form/schema.py
caluma/workflow/schema.py

Each connection has its own FilterSet so filter_fields is not needed anymore.

Remove obsolete filter fields configuration

---

.travis.yml

Fixes #34 
Helps to solve later merge conflicts when several PRs will try to add the same migrations.

Check that there are no missing migrations

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/models.py
caluma/workflow/schema.py
caluma/workflow/tests/snapshots/snap_test_workflow.py
caluma/workflow/tests/test_workflow.py

Fixes #281 
This returns all tasks which are referenced in a workflow. That this works
all jexl expression need to be analyzed for referencing tasks.

Add workflow tasks list node

---

.gitignore
CONTRIBUTING.md

We don't want to commit IDE specific configurations.
Fixed typo in CONTRIBUTING.md

Add .idea/ to .gitignore

---

docker-compose.override.yml
docker-compose.yml

This makes it easier to work simultaniously on multiple projects
with postgres.

Configure postgres port via envvar in dev

---

caluma/core/filters.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
caluma/workflow/tests/test_work_item.py

Fixes #292
This filter uses the `__overlap` lookup expression.
This commit implements a function `_generate_list_filter_class(inner_type)`
to generate Filter classes that will resolve into graphene type lists.
For now we only need a `StringListFilter`.

Filter workitems by assigned_groups

---

caluma/core/filters.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/tests/test_base_filters.py

Those fields are in the BaseModel, so the filters are available for all models.
Closes #296

Add filters for created_by_user, created_by_group

---

caluma/form/serializers.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_question.py

This hasn't been tested yet and never worked.

Fix SaveTableQuestion mutation

---

caluma/form/storage_clients.py

Changes:
- call correct method in recursive methods
- handle `minio.error.NoSuchBucket` everywhere

Fixes for minio client

---

caluma/form/jexl.py
caluma/form/tests/test_jexl.py
caluma/form/tests/test_validators.py
caluma/form/validators.py
caluma/workflow/validators.py

See https://github.com/projectcaluma/ember-caluma/pull/154 for the corresponding frontend implementation.

feat(jexl): add support for nested forms

---

caluma/form/jexl.py
caluma/form/tests/test_jexl.py

feat(jexl): add "intersects" binary operator

---

caluma/form/serializers.py

This commit fixes a regression from #410.

Do only recreate the File object if the file name changed

---

caluma/form/filters.py
caluma/form/tests/test_document.py
caluma/tests/snapshots/snap_test_schema.py

This commit implements a filter for filtering answers based on mutliple
question slugs.
Closes #420

Filter answers based on multiple question slugs

---

caluma/form/jexl.py
caluma/form/tests/test_jexl.py
caluma/form/tests/test_validators.py
caluma/form/validators.py

Various fixes and improvements in question JEXL evaluation

Jexl evaluation stability

---

caluma/form/factories.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/test_document.py
caluma/form/tests/test_type.py

This commit simplifies `resolve_answer()`. The answer type is now mapped onto
question type.
While doing this I've found and fixed a bug in a test thatfailed
after this change.

fix(form): fix answer resolving

---

caluma/form/migrations/0018_remove_answer_value_document_data_migration.py

The previous version would choke if the ordering of answers wasn't
strictly top-to-bottom. Also, answers would only be moved one level up,
while they should be moved to the top document instead

Fix migration for flattening document hierarchies

---

caluma/form/schema.py
caluma/form/serializers.py
caluma/form/tests/test_document.py
caluma/tests/snapshots/snap_test_schema.py

Add removeDocument mutation

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py
caluma/workflow/tests/test_case.py

This filter returns all cases where the associated document's form slug
equals the requested value
/cc @anehx

feat(filters): New documentForm filter on allCases

---

caluma/core/filters.py
caluma/tests/snapshots/snap_test_schema.py

feat(filters): Meta lookup: extend to LT,GT,LTE,GTE

---

caluma/core/filters.py
caluma/form/tests/snapshots/snap_test_filter_by_answer.py
caluma/form/tests/test_filter_by_answer.py
caluma/tests/snapshots/snap_test_schema.py

feat: hasAnswers filter: Extend with lookup mode INTERSECTS

---

README.md

We use travis-ci.com and not org anymore

Adjust invalid Travid badge link

---

caluma/core/filters.py
caluma/core/tests/test_pagination.py
caluma/tests/snapshots/snap_test_schema.py

BREaKING CHANGE use relay pagination instead
Fixes #531
Caluma recommends to use relay pagination so requirements should be adjusted accordingly.
/cc @anehx @czosel

fix!: Remove erroneous offset and limit pagination filters

---

renovate.json
requirements-dev.txt

This works around issue [0] till it is fixed upstream
[0] https://gitlab.com/pycqa/flake8-docstrings/issues/36

chore(ci): Pin pydocstyle to fix CI

---

caluma/core/filters.py
caluma/form/schema.py
caluma/form/tests/test_document.py

This is an approximate performance improvement of 5%

fix: Avoid form queries when querying table and form questions

---

caluma/core/filters.py

Extract queryset from manager when no filters are set

---

caluma/form/serializers.py

Document why family needs to be set without using update

---

caluma/form/serializers.py
caluma/form/tests/test_document.py

Under certain conditions (which are not fully understood until now) the
main documents' family was changed when an enclosed table question was
updated.
This adds a test that demonstrates the flaky behaviour, and a bugfix
that fixes it and tries to clarify the code.

fix(table): fix flaky detaching of documents when updating TableAnswers

---

caluma/form/serializers.py
caluma/form/tests/test_document.py

Avoiding exception when tables in tables are used.

Set document family properly on whole family

---

caluma/core/filters.py
caluma/form/filters.py
caluma/form/tests/test_filter_by_answer.py
caluma/workflow/filters.py

Fixes #530
As the answer filter is specific to form it needs to be in that app to avoid circular dependencies.

Move HasAnswerFilter and all its deps to form app

---

caluma/form/jexl.py
caluma/form/tests/test_validators.py
caluma/form/validators.py

Fixes #609 
Based on #625 which needs to be merged first

Do not swallow question is missing exception

---

caluma/settings.py
caluma/urls.py
caluma/user/tests/test_views.py
caluma/user/views.py

Fixes #477
For this needed to replace middleware with an extended django view
where a response can be handled directly.

Return 401 status code when authentication failed

---

caluma/user/models.py

Caluma always wants to access the `group` property on the user object.
Since the `OIDCClient` has no `group` this currently leads to an error.
Add the `group` for all user objects and make a minor refactoring to
ensure every user object has the same properties.

fix(user-models): add missing group to OIDCClient

---

caluma/form/filters.py
caluma/form/tests/test_search_answers.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py

BREAKING: Rename the SearchAnswerFilterType to SearchAnswersFilterType
BREAKING: searchAnswers filter now takes a list instead of an object
fixes #655

feat(searchAnswers): Allow multiple searches

---

caluma/form/tests/test_search_answers.py

chore(tests): Add test for searchAnswers with multiple params

---

caluma/form/historical_schema.py
caluma/form/tests/snapshots/snap_test_history.py
caluma/form/tests/test_history.py

This commit makes sure that also removed records are included in
historical responses.

fix(history): do not hide removed records

---

.travis.yml
caluma/caluma_metadata.py
requirements-dev.txt
setup.cfg
setup.py

Single source project metadata and introduce [python-semantic-release](https://github.com/relekang/python-semantic-release).

Release preparations

---

caluma/core/management/commands/cleanup_history.py
caluma/form/tests/test_command.py

fixes https://github.com/projectcaluma/caluma/issues/715

fix(history): cleanup_history - add force argument

---

.flake8
README.md
caluma/core/filters.py
caluma/core/tests/test_inversible_filters.py
caluma/form/filters.py
caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/schema.py
docs/graphql.md

This introduces filters that can be chained (same filter multiple times)
and negated.  Currently this is VERY WIP, but shows what can be done in
the allDocuments edge.
Code needs to be cleaned up and applied to the other filterable edges as well,
and tests adjusted etc..

Filter cleanup and negation

---

caluma/data_source/data_source_handlers.py
caluma/data_source/data_sources.py
caluma/data_source/schema.py
caluma/data_source/tests/data_sources.py
caluma/data_source/tests/snapshots/snap_test_data_source.py
caluma/data_source/tests/test_cache_decorator.py
caluma/data_source/tests/test_data_source.py
caluma/data_source/utils.py
caluma/form/schema.py
caluma/form/tests/snapshots/snap_test_question.py
caluma/form/tests/test_document.py
caluma/form/tests/test_question.py
caluma/form/tests/test_validators.py
caluma/form/validators.py
caluma/tests/snapshots/snap_test_schema.py
docs/extending.md

feat(data_source): add the answer id to the data source

---

caluma/conftest.py
caluma/core/jexl.py
caluma/core/mutation.py
caluma/core/tests/fake_model.py
caluma/form/jexl.py
caluma/form/tests/test_document.py
caluma/form/validators.py
requirements-dev.txt

This commit introduces
[flake8-bugbear](https://github.com/PyCQA/flake8-bugbear).

chore: introduce flake8-bugbear

---

caluma/form/tests/test_validators.py
caluma/form/validators.py

We should only validate answers that are visible.

Fix 731 form validation

---

caluma/form/schema.py
caluma/tests/snapshots/snap_test_schema.py

dynamic options should be exposed on Document, Answers and Questions.

fix(schema): remove dynamicoptionSet form schema

---

caluma/data_source/tests/test_data_source.py
caluma/form/validators.py

Add the user and the group when a dynamic option was created.

fix(data souce): add user and group to dynamic option

---

.reuse/dep5
LICENSES/GFDL-1.3-or-later.txt

GPL cannot apply to documentation since there are no runtime artifacts

chore(reuse): Use GFDL license for documentation

---

caluma/core/jexl.py
caluma/form/jexl.py
caluma/form/tests/test_jexl.py
caluma/form/tests/test_validators.py
caluma/form/validators.py

Fix evaluate is_hidden

---

caluma/form/historical_schema.py

This commit prevents duplicate documents in `HistoricalTableAnswer`.
Closes #798

fix(history): fix duplicate documents

---

caluma/tests/snapshots/snap_test_schema.py
caluma/workflow/filters.py

Fixes #802 by adding those filters. Even though it only requested
the created_at filter, the other date-based filters also make sense

feat: add created_at, closed_at, modified_at filters to work items

---

caluma/form/filters.py
caluma/form/tests/snapshots/snap_test_document.py
caluma/form/tests/test_filter_by_answer.py
caluma/form/validators.py
caluma/tests/snapshots/snap_test_schema.py

based on https://github.com/projectcaluma/caluma/pull/821

Filter visible in context

---

CONTRIBUTING.md
requirements-dev.txt
setup.cfg

pytest-django creates a database per worker by default: https://git.io/Je9cn

feat(pytest): run pytest in parallel with xdist

---

caluma/caluma_metadata.py

Try to get semantic-release back to working state

fix(release): version bump

---

.reuse/dep5
CHANGELOG.md
README.md
caluma/caluma_metadata.py
docs/maintainers.md

Note: I've added documentation on HOWTO release, please verify that as well

Release 5.0.0

---

caluma/caluma_form/jexl.py
caluma/caluma_form/models.py
caluma/caluma_form/structure.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

This should speed up validation significantly :)

Validation performance fixes

---

caluma/caluma_workflow/filters.py
caluma/caluma_workflow/tests/test_case.py
caluma/tests/snapshots/snap_test_schema.py

Add the `HasAnswerFilter` on `allCases` with configuration to look for answers
in one of the associated work items
Fixes #908

feat(filters): new filter on cases to check for answers in work items

---

MANIFEST.in
setup.py

This commit adds `long_description` and `download_url` to setup.py.
Additionally it fixes a wrongly referenced file in `MANIFEST.in` and makes sure excludes are at the bottom of the file.

chore(pypi): more improvements to setup.py

---

CHANGELOG.md
caluma/caluma_metadata.py

chore(release): version 5.4.0

---

caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_jexl.py

Questions which have multiple values (multiple choice and table) need to
return an empty list when hidden so transforms like `intersects` or
`mapby` don't raise an exception. Also this commit adds a missing test
for mapby and makes the transform a bit more defensive.

fix(jexl): fix answer transform for questions with multiple values

---

requirements-dev.txt
requirements.txt

See #1002, #1008, #1012, #1013

chore(deps): update various deps

---

caluma/caluma_form/historical_schema.py
caluma/caluma_form/schema.py
caluma/caluma_form/tests/test_history.py

Use correct historical question for finding answer type.

fix(historical): use matching question for historicalanswer

---

caluma/caluma_core/tests/test_validations.py
caluma/caluma_core/tests/test_visibility.py
caluma/caluma_core/validations.py
caluma/caluma_core/visibilities.py

Make `@filter_queryset_for` and `@validation_for` chainable for reuse.
The same method can now be reused for multiple Node types / Mutations.

feat: make validation and visibility decorators chainable

---

caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/tests/test_work_item.py

This fixes two issues:
1) When completing a work item, we didn't consider it's associated
workflow when searching for sibling tasks. This means that if the
same task is used in multiple workflows, task flows used in any of
those workflows would be evaluated.
2) When completing a "leaf" work item (i.e. no attached flows) we only
checked if all sibling work items are complete. However, we have to
check if _any_ work items are still open ("READY") before we can
complete a workflow.

fix(workflow): consider workflow when completing work items

---

caluma/caluma_workflow/api.py

Voilà!
https://github.com/projectcaluma/caluma/pull/1127#discussion_r462837424

fix(history): fix history by not using djangos update function

---

caluma/caluma_workflow/api.py
caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/schema.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/test_work_item.py
caluma/tests/__snapshots__/test_schema.ambr
docs/events.md

feat(workflow): add mutation and api function for canceling work items

---

caluma/caluma_workflow/tests/__snapshots__/test_workflow.ambr
caluma/caluma_workflow/tests/test_workflow.py
caluma/conftest.py

Fixes flakiness like found here:
https://travis-ci.com/github/projectcaluma/caluma/jobs/366493032

fix(tests): fix flakiness by sorting the list during snapshotting

---

docs/workflow-concepts.md

This intro section is already written [here](https://github.com/projectcaluma/caluma/blob/master/docs/workflow-implementation.md) which is linked in the section above..

docs(workflow): remove duplicated intro section

---

caluma/caluma_workflow/dynamic_groups.py
caluma/caluma_workflow/jexl.py

This is a follow up for #1133 
@winged I refactored the transform the same way you requested it for the task(s) transforms
@open-dynaMIX I added a docstring for the base class for dynamic groups

chore: add docs for extension class and improve groups transform

---

caluma/caluma_workflow/domain_logic.py

fix(workflow): emit completed_work_item event before closing the case

---

CHANGELOG.md
caluma/caluma_metadata.py

chore: release 6.3.2

---

caluma/caluma_workflow/domain_logic.py
caluma/caluma_workflow/tests/test_events.py

fix: don't send complete_work_item event when skip

---

caluma/caluma_core/management/commands/migrate_to_prefixed_apps.py
caluma/caluma_core/tests/test_migrate_to_prefixed_apps.py

fix: migrate db sequences with prefix "caluma_"

---

caluma/caluma_workflow/migrations/0020_case_families.py
caluma/caluma_workflow/tests/test_migrations.py

Some data was even worse so the fix from the previous PR[1] didn't
catch 100% of the cases. This fix addresses the issue and is able
to process the broken data as expected.
[1]:https://github.com/projectcaluma/caluma/pull/1215

fix: do not crash during migrations

---

setup.cfg
setup.py

Splitting the config between setup.py and setup.cfg didn't work out as planned, the resulting package on pypi had no caluma source.
So move to a complete setup.py config instead

fix(package): move deps to setup.py

---

CHANGELOG.md
caluma/caluma_metadata.py

* Move deps to setup.py ([`39e46f3`](https://github.com/projectcaluma/caluma/commit/39e46f39dd192c0b22393f05b4f401e0b55cf8d3))

chore(release): v7.0.1

---

caluma/caluma_form/domain_logic.py
caluma/caluma_form/tests/__snapshots__/test_document.ambr
caluma/caluma_form/tests/test_document.py

This fixes a regression introduced in 6b71559eb7a1dca280de625c89d7b4e65c02decc

fix(form): fix empty answers

---

caluma/caluma_form/serializers.py
caluma/caluma_form/tests/test_answer.py

Fixes a regression introduced in 6b71559eb7a1dca280de625c89d7b4e65c02decc

fix(validation): fix custom validation for save answer mutations

---

caluma/caluma_form/filters.py
caluma/caluma_form/tests/test_search_answers.py

Add support for searching multiple choice questions (both dynamic and
static). And while we're at it, also change the lookup of choice value
to use the option's label instead of the slug, which ought to be much
more useful.
Note: This implies that the label is present in the user's current language, otherwise it won't find possible matches.

Feat: Support text search in question options, Support multiple choice

---

caluma/caluma_core/jexl.py
caluma/caluma_core/tests/test_jexl.py
caluma/caluma_form/jexl.py
caluma/caluma_form/tests/test_answer.py
caluma/caluma_form/tests/test_jexl.py
caluma/caluma_form/tests/test_validators.py
caluma/caluma_form/validators.py

Drop calc answer validation, add useful jexl transforms

---

CHANGELOG.md
caluma/caluma_metadata.py

chore: release 7.7.1

---

caluma/caluma_form/storage_clients.py

Use CopySource now instead of the old "bucket/object_name" string syntax
when copying / moving files in Minio.

fix(minio): minio client requires different call signature for copy

---

.gitlint

Follow-up https://github.com/projectcaluma/caluma/pull/1433

chore: fix ignore line for gitlint

---

caluma/caluma_form/models.py
caluma/caluma_form/tests/test_model.py

If no file is uploaded to the storage service, we want to ignore the resulting
exceptions in order to still be able to modify/delete the File.

fix(file): ignore errors due to missing file

---

CHANGELOG.md
caluma/caluma_metadata.py

* **form:** Modified_content on row documents ([`75822ef`](https://github.com/projectcaluma/caluma/commit/75822efd29bc5cfc96af205631cfb4975666b43a))
* **file:** Ignore errors due to missing file ([#1440](https://github.com/projectcaluma/caluma/issues/1440)) ([`63d9f94`](https://github.com/projectcaluma/caluma/commit/63d9f94a5fb7de749dd2074f28acdaebd3409ec5))

chore(release): v7.8.1

---

setup.py

See https://github.com/psycopg/psycopg2/issues/1293#issuecomment-862835147

chore(ci): fix pipeline by locking psycopg2-binary

---

README.md
docker-compose.yml

Also added set the DEV flag to true in the example `docker-compose.yml` file, which is something that I struggled with at the start.
However, that change is perhaps controversial.

fix(documentation): Updated readme to reflect that GraphiQL is not available anymore

---

CHANGELOG.md

They are not relevant to users/devs, as those features
are not part of the code right now (even if there are commits...)

chore: remove reverted changes from changelog

---

caluma/caluma_form/format_validators.py
caluma/caluma_form/migrations/0044_migrate_format_validators.py
caluma/caluma_form/tests/__snapshots__/test_format_validators.ambr
caluma/caluma_form/tests/__snapshots__/test_question.ambr

Related to https://github.com/projectcaluma/ember-caluma/pull/1779

Fix validators

---

caluma/caluma_form/filters.py
caluma/caluma_form/tests/__snapshots__/test_filter_by_answer.ambr
caluma/caluma_form/tests/test_filter_by_answer.py
caluma/tests/__snapshots__/test_schema.ambr

fix: restrict valid filters for choice questions

---

.github/workflows/tests.yml

chore(ci): add compatibility tests for python up to version 3.10

---

caluma/caluma_form/models.py

This caused some kind of query loop that resulted in very slow DB queries.

fix(document): remove duplicate filtering on answer

---

caluma/conftest.py

Similar to the existing at_date() fixture, the new set_date() fixture
works as a context manager and allows more complex code to run within
a given faked datetime.

feat(test): fixture for running a block of code at a given faked time

---

caluma/conftest.py

I still kind of like it, but it's currently unused, and just keeping stuff
around because it "might" be used later on is kind of a bad idea

chore: remove unused fixture

---

CHANGELOG.md
pyproject.toml

@winged I had to write the "breaking" part of the changelog myself since semantic release couldn't handle it ^^

chore(release): v8.0.0-beta.6

---

caluma/caluma_form/historical_schema.py
caluma/tests/__snapshots__/test_schema.ambr
poetry.lock

This will update graphene which results in a change of the schema which should be uncritical.

fix(deps): update dependencies of dependencies

---

caluma/caluma_form/filters.py
caluma/tests/__snapshots__/test_schema.ambr

fixes bug from #656
not sure if breaking?

fix(form): set questions of searchAnswers as required

---

caluma/caluma_form/filters.py
caluma/caluma_form/models.py
caluma/caluma_form/tests/test_search_answers.py
caluma/tests/__snapshots__/test_schema.ambr

This is the result of a hacking-session with @winged. I didn't have the time to finish this before the holidays.
@Yelinz This is needed for mySAGW. Would be great if you could push this forward, maybe with additional help from a backender.

feat: searchanswers in forms

---

caluma/caluma_form/migrations/0046_file_answer_reverse_keys.py
caluma/caluma_form/tests/test_migrate_to_multiple_files.py

The previous approach ignored all HistoricalFiles that belong to an
Answer that doesn't exist anymore.
This approach takes all HistoricalFiles into account and hence provides
a more robust procedure.

fix: fix multifile migration again

---

caluma/caluma_workflow/filters.py
caluma/tests/__snapshots__/test_schema.ambr

Should just work like this right?

feat(workflow): add search answer filter to work item filters

---

caluma/caluma_core/events.py
caluma/caluma_user/models.py
caluma/caluma_workflow/schema.py
caluma/caluma_workflow/serializers.py
caluma/caluma_workflow/tests/__snapshots__/test_case.ambr
caluma/caluma_workflow/tests/test_case.py
caluma/tests/__snapshots__/test_schema.ambr

We need to discuss whether the python API `start_case` should be renamed to `save_case` to be consistent with the GraphQL API. What is your take on this @winged @open-dynaMIX @fugal-dy @czosel ?
Resolves #930

Remove various deprecations

---

caluma/caluma_user/permissions.py
caluma/caluma_user/tests/test_permissions.py

fix(permissions): make sure user permission classes call super

---

caluma/caluma_analytics/simple_table.py
caluma/caluma_analytics/sql.py
caluma/caluma_analytics/tests/test_form_field_extraction.py
caluma/caluma_analytics/tests/test_simple_table.py
caluma/caluma_analytics/visibility.py

Analytics now gives you the ability to not only extract slugs from choice
questions, but the corresponding labels as well.

feat(analytics): provide option labels

---

.github/workflows/compatibility-tests.yml
.github/workflows/pypi.yml
.github/workflows/tests.yml

This is the recommended way of caching poetry dependencies in github actions

chore(ci): use built in cache of setup-python action

---

caluma/caluma_analytics/management/commands/run_analytics.py

The run_analytics command used the column aliases as keys in the format string for outputting tabular data. This crashes if the aliases contain values (like dots, etc) that are not compatible with format string syntax. Thus, we hash the aliases before using it in the format string. A little less debuggable, but guaranteed valid keys.

fix(analytics): fix commandline output crash with certain aliases

---

caluma/caluma_analytics/conftest.py
caluma/caluma_analytics/simple_table.py
caluma/caluma_analytics/tests/__snapshots__/test_simple_table.ambr
caluma/caluma_analytics/tests/test_simple_table.py

This commit implements support for using multiple keys from the meta field.
Closes #2017

fix(analytics): fix meta field extraction

---

caluma/caluma_core/filters.py
caluma/caluma_core/tests/test_meta_filters.py
caluma/tests/__snapshots__/test_schema.ambr

Motivation: Just like Answers, filtering with an intersection in the meta is useful

feat(core): add meta intersection filter

---

CHANGELOG.md
pyproject.toml

* **core:** Add meta intersection filter ([`1a54a7f`](https://github.com/projectcaluma/caluma/commit/1a54a7f1798d4f816a29e2c68935294899fa2a88))
* **analytics:** Fix meta field extraction ([`704ffb9`](https://github.com/projectcaluma/caluma/commit/704ffb907d7863f9928fe10bb8826e226c286cb0))

chore(release): v9.2.0

---

caluma/caluma_user/views.py
caluma/settings/caluma.py

Work by @derrabauke, Stacks on top of #2133

Feat disable introspection

---

caluma/caluma_user/tests/test_views.py
caluma/caluma_user/views.py

The `DisableIntrospection` validator rejects everything that could lead to insight into the schema. Sadly, our frontends rely on having `__typename` available, thus we need our own validator that allows this specific introspection key (but not anything else)

fix(validation): do not block __typename when introspection is disabled

---

caluma/caluma_form/models.py

Instead of triggering calculations every time a table answer is copied, only once at the end then the calculation is run.

fix(form: speed up copying of documents

---

caluma/caluma_user/views.py

We use a "global" requests session for auth, as the initialisation of SSL context and re-opening of a TCP connection to the OIDC IDP can cause some additional load (and work time) that we want to avoid if possible.

feat(perf): keep auth http session alive across requests
